-- attest_tag baseline schema, Postgres.
--
-- The twin of ../sqlite/0001_baseline.sql, converted mechanically: integer -> bigint (SQLite
-- integers are 64-bit, and several of these columns hold UnixNano, which overflows a 32-bit
-- integer), real -> double precision, blob -> bytea, and SQLite's
-- "integer primary key autoincrement" -> "bigint generated by default as identity". By default
-- rather than always, so that an import can carry the ids a database already has.
--
-- The timestamp default produces the same text in the same format as SQLite's datetime('now'),
-- because timestamps here are stored as text and compared as text. Changing that to a real
-- timestamp type is a separate migration, deliberately not folded into this one.

create table access_request_cards (
  org_id     bigint not null,
  request_id bigint not null,
  approver   text not null,
  channel    text not null,
  ts         text not null,
  primary key (request_id, approver)
);
create table access_requests (
  id         bigint generated by default as identity primary key,
  org_id     bigint not null,
  team_id    text not null default '',
  channel    text not null, thread_ts text not null,
  requester  text not null,
  approver   text not null default '',
  approvers  text not null default '[]',
  what       text default '',
  why        text default '',
  ask        text default '',
  calls      text not null default '[]',
  status     text not null default 'pending',
  origin_ts  text default '',
  decided_by text default '', decided_at text,
  reason     text default '',
  result     text default '',
  created_at text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  expires_at text not null
, self_approved bigint default 0, role_id bigint default 0);
create table admin_sessions (
  token text primary key,
  id bigint not null default 0,
  org_id bigint not null default 0,
  user_id text, name text, email text,
  created_at text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')), expires_at text not null
, mfa_verified bigint not null default 0, via text not null default '');
create table alerts_sent (
  org_id bigint not null,
  key text not null, created_at text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  primary key (org_id, key)
);
create table api_keys (
  id           bigint generated by default as identity primary key,
  org_id       bigint not null,
  user_id      bigint not null,
  name         text not null,
  key_hash     text not null,
  key_prefix   text not null default '',
  last_used_at text,
  expires_at   text,
  revoked_at   text,
  created_by   text default '',
  created_at   text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);
create table approval_members (
  id         bigint generated by default as identity primary key,
  org_id     bigint not null,
  role_id    bigint not null,
  ref        text not null,
  created_at text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
, team_id text not null default '', slack_user_id text not null default '');
create table approval_role_bundles (
  org_id  bigint not null,
  role_id bigint not null, bundle_id bigint not null,
  primary key (role_id, bundle_id)
);
create table approval_role_connections (
  org_id  bigint not null,
  role_id bigint not null, connection_id bigint not null,
  primary key (role_id, connection_id)
);
create table approval_roles (
  id         bigint generated by default as identity primary key,
  org_id     bigint not null,
  name       text not null,
  rank       bigint not null default 1,
  bundle_id  bigint not null default 0,
  created_at text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);
create table artifacts (
  id         bigint generated by default as identity primary key,
  org_id     bigint not null,
  team_id    text not null default '',
  channel    text, thread_ts text, created_by text,
  title      text not null,
  kind       text not null default 'md',
  bytes      bigint default 0,
  content    text not null default '',
  file_id    text default '',
  permalink  text default '',
  created_at text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);
create table bundles (
  id           bigint generated by default as identity primary key,
  org_id bigint not null,
  name         text not null,
  instructions text default '',
  tool_packs   text default '[]',
  created_by   text,
  created_at   text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at   text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);
create table connect_states (
  state         text primary key,
  org_id        bigint not null,
  conn_id       bigint not null,
  team_id       text not null default '',
  slack_user_id text not null,
  verifier      text not null,
  redirect_uri  text not null default '',
  created_at    text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  expires_at    text not null
);
create table connections (
  id            bigint generated by default as identity primary key,
  org_id  bigint not null,
  bundle_id     bigint not null,
  name          text not null,
  preset        text default 'custom',
  cred_type     text not null,
  secret_enc    bytea,
  allowed_hosts text default '[]',
  path_prefixes text default '[]',
  methods       text default '[]',
  headers       text default '[]',
  writes        text default 'confirm',
  notes         text default '',
  status        text default 'active',
  last_used     text,
  created_by    text,
  created_at    text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at    text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
, repo text default '', github_installation_id bigint not null default 0, allow_grants bigint default 0, test_cmd text default '', recipe text default '');
create table console_invites (
  id            bigint generated by default as identity primary key,
  token_hash    text not null unique,
  team_id       text not null default '',
  slack_user_id text default '',
  email         text default '',
  role          text not null default 'viewer',
  created_by    text default '',
  created_at    text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  expires_at    text not null,
  accepted_at   text, accepted_by text default '',
  revoked_at    text
);
create table console_roles (
  id          bigint generated by default as identity primary key,
  org_id      bigint not null,
  key         text not null,
  label       text not null,
  permissions text not null default '[]',
  created_by  text default '',
  created_at  text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);
create table console_users (
  id            bigint generated by default as identity primary key,
  org_id  bigint not null,
  team_id       text not null default '',
  slack_user_id text not null,
  email         text default '',
  name          text default '',
  role          text not null default 'viewer',
  created_by    text default '',
  created_at    text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  last_seen     text
);
create table doc_chunks (
  id          bigint generated by default as identity primary key,
  org_id      bigint not null,
  source      text, doc_id text, url text, title text, heading text,
  chunk       text not null,
  hash        text not null,
  acl         text default '',
  embedding   bytea,
  updated_at  text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);
create table document_folders (
  id         bigint generated by default as identity primary key,
  org_id     bigint not null,
  path       text not null,
  created_at text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);
create table documents (
  id          bigint generated by default as identity primary key,
  org_id bigint not null,
  path        text not null,
  name        text not null,
  size        bigint default 0,
  uploaded_by text,
  scope       text default '',
  status      text default 'pending',
  chunks      bigint default 0,
  last_error  text default '',
  updated_at  text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);
create table domains (
  id        bigint generated by default as identity primary key,
  org_id bigint not null,
  bundle_id bigint not null,
  host      text not null,
  ports     text default '443'
);
create table drive_sync_files (
  id       bigint generated by default as identity primary key,
  org_id   bigint not null,
  sync_id  bigint not null,
  file_id  text not null,
  path     text not null,
  version  text default '',
  seen_at  text
);
create table drive_syncs (
  id            bigint generated by default as identity primary key,
  org_id        bigint not null,
  connection_id bigint not null,
  folder_id     text not null,
  folder_name   text default '',
  dest          text not null default '',
  scope         text not null default '',
  recurse       bigint not null default 1,
  enabled       bigint not null default 1,
  last_run      text,
  last_status   text default '',
  last_error    text default '',
  last_added    bigint default 0, last_updated bigint default 0, last_removed bigint default 0,
  created_by    text,
  created_at    text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);
create table email_tokens (
  -- Postgres has no rowid, and this table's primary key is the token hash, so the surrogate the
  -- console revokes an invitation by has to be a real column. SQLite uses its rowid for the same
  -- purpose; emailTokenIDCol in db_dialect.go is the one place that knows which.
  id bigint generated by default as identity unique,
  token_hash text primary key,
  kind       text not null,
  user_id    bigint not null default 0,
  org_id     bigint not null default 0,
  email      text default '',
  slack_user_id text default '',
  role       text default '',
  label      text default '',
  domain     text default '',
  max_uses   bigint not null default 1,
  uses       bigint not null default 0,
  created_by bigint not null default 0,
  created_at text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  expires_at text not null,
  used_at    text
);
create table file_texts (
  team_id text not null default '', file_id text not null, name text, text text,
  created_at text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  primary key (team_id, file_id)
);
create table github_installs (
  installation_id bigint primary key,
  org_id bigint not null,
  account_login text default '', account_id bigint default 0, account_type text default '',
  repo_selection text default '',
  permissions text default '',
  app_slug text default '', installed_by text default '',
  suspended_at text, status text default 'active', last_error text,
  installed_at text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')), revoked_at text );
create table investigations (
  id bigint generated by default as identity primary key,
  status text not null default 'queued',
  org_id bigint not null,
  team_id text not null default '', channel text not null, thread_ts text not null,
  requester text default '',
  question text not null, brief text default '',
  rounds bigint default 0, minutes bigint default 0,
  attempts bigint default 0, lease_until bigint not null default 0,
  tokens_in bigint default 0, tokens_out bigint default 0, cost_usd double precision default 0,
  error text default '',
  created_at text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')), started_at text default '', finished_at text default ''
);
create table job_events (
  id bigint generated by default as identity primary key, org_id bigint not null, job_id bigint not null, seq bigint not null,
  kind text not null,
  phase text default '', status text default '',
  message text default '', data text default '{}', at text default '',
  tokens_in bigint default 0, tokens_out bigint default 0, cost_usd double precision default 0,
  created_at text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);
create table job_files (
  org_id bigint not null, job_id bigint not null, kind text not null,
  bytes bigint default 0, content text default '', file_id text default '', permalink text default '',
  created_at text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);
create table jobs (
  id bigint generated by default as identity primary key,
  status text not null default 'queued',
  org_id bigint not null,
  team_id text not null default '', channel text not null, thread_ts text not null,
  requester text default '', approved_by text default '', approval text default '',
  connection_id bigint not null, repo text not null, base_branch text default '', branch text default '', title text default '',
  spec text not null,
  engine text default '', model text default '', budget_usd double precision default 0, timeout_s bigint default 0, draft_pr bigint default 1,
  dispatcher text default '', execution_ref text default '',
  token_hash text default '', token_expires text, claimed_at text, claim_count bigint default 0, worker_info text default '',
  status_ts text default '', phase text default '', last_seq bigint default 0, last_event_at text,
  cancel_requested bigint default 0, cancel_by text default '', cancel_reason text default '', cancel_requested_at text,
  result text default '', pr_url text default '', error text default '',
  cost_usd double precision default 0, tokens_in bigint default 0, tokens_out bigint default 0,
  llm_key_hash text default '', llm_key_enc bytea,
  created_at text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')), started_at text, finished_at text
);
create table login_challenges (
  token      text primary key,
  user_id    bigint not null,
  tries      bigint not null default 0,
  created_at text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  expires_at text not null
, via text not null default 'password');
create table memberships (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null,
  org_id     bigint not null,
  role       text not null default 'viewer',
  created_by bigint not null default 0,
  created_at text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);
create table memories (
  id          bigint generated by default as identity primary key,
  org_id      bigint not null,
  team_id     text not null default '',
  scope       text not null,
  text        text not null,
  created_by  text,
  created_at  text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);
create table oauth_states (
  state        text primary key,
  org_id bigint not null,
  created_by   text default '',
  created_at   text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  expires_at   text not null
);
create table orgs (
  id          bigint generated by default as identity primary key,
  public_id   text not null default '',
  name        text not null,
  slug        text not null,
  status      text not null default 'active',
  plan        text not null default 'free',
  plan_budget_usd double precision not null default 0,
  created_by  bigint not null default 0,
  created_at  text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);
create table pending_writes (
  id bigint generated by default as identity primary key,
  org_id bigint not null,
  team_id text not null default '',
  channel text, thread_ts text, requester text, request text,
  status text default 'pending', created_at text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);
create table personal_memories (
  id          bigint generated by default as identity primary key,
  org_id      bigint not null,
  team_id     text not null,
  owner       text not null,
  text        text not null,
  created_at  text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at  text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);
create table proxy_audit (
  id            bigint generated by default as identity primary key,
  org_id bigint not null,
  team_id text not null default '', channel text, thread_ts text, requester text,
  connection_id bigint, method text, host text, path text,
  status bigint, ms bigint, blocked text default '',
  created_at    text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
, access_request_id bigint default 0);
create table routine_runs (
  id          bigint generated by default as identity primary key,
  org_id      bigint not null,
  routine_id  bigint not null,
  team_id     text not null default '',
  channel     text not null default '',
  thread_ts   text not null default '',
  status      text not null default '',
  reason      text default '',
  output      text default '',
  error       text default '',
  tokens_in   bigint default 0,
  tokens_out  bigint default 0,
  cost_usd    double precision default 0,
  started_at  text,
  finished_at text,
  ms          bigint default 0
);
create table routines (
  id          bigint generated by default as identity primary key,
  org_id      bigint not null,
  team_id     text not null default '',
  channel     text not null,
  cron        text not null,
  tz          text default 'Asia/Kathmandu',
  prompt      text not null,
  created_by  text,
  enabled     bigint default 1,
  next_run    text,
  last_run    text,
  last_error  text
, result_ts text, notify text not null default 'always', notify_when text default '', last_status text default '', auto_confirm bigint not null default 0, steps text not null default '[]', finish text not null default 'answer', model text not null default '');
create table scope_bundles (
  org_id bigint not null,
  scope_id bigint not null, bundle_id bigint not null,
  primary key (scope_id, bundle_id)
);
create table scope_connections (
  org_id bigint not null,
  scope_id bigint not null, connection_id bigint not null,
  primary key (scope_id, connection_id)
);
create table scopes (
  id            bigint generated by default as identity primary key,
  org_id  bigint not null,
  kind          text not null,
  team_id       text not null default '',
  slack_id      text not null default '',
  name          text,
  is_private    bigint not null default 0,
  instructions  text default '',
  default_model text default '',
  member_edits  text default 'inherit',
  read_all      text default 'inherit',
  max_tool_rounds bigint not null default 0,
  created_at    text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
, link_epoch bigint not null default 0, monthly_budget_usd double precision default 0, allow_rules text default '[]', default_repo text default '', approvers text default '', left_at text not null default '');
create table seen_events (
  key text primary key, created_at text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  owner text not null default ''
);
create table sessions (
  team_id     text not null default '',
  channel     text not null,
  thread_ts   text not null,
  kind        text not null,
  model       text,
  status      text default 'active',
  muted       bigint default 0,
  title       text,
  tool_calls  bigint default 0,
  created_at  text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  last_active text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')), summary text default '', summary_upto text default '',
  primary key (team_id, channel, thread_ts)
);
create table settings (
  org_id bigint not null, key text not null,
  value text not null, updated_at text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  primary key (org_id, key)
);
create table setup_links (
  token text primary key, org_id bigint not null, bundle_id bigint, preset text, name text,
  created_by text, status text default 'pending', connection_id bigint,
  created_at text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')), expires_at text not null
);
create table skills (
  id        bigint generated by default as identity primary key,
  org_id bigint not null,
  bundle_id bigint not null,
  name      text not null,
  content   text not null,
  enabled   bigint default 1,
  updated_at text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);
create table slack_deliveries (
  delivery_key text primary key,
  team_id text not null,
  org_id bigint not null default 0,
  kind text not null,
  payload_enc bytea,
  accepted_at bigint not null,
  lease_until bigint not null default 0,
  done_at bigint not null default 0,
  attempts bigint not null default 0,
  dead_at bigint not null default 0,
  last_error text not null default ''
);
create table teams (
  team_id       text primary key,
  org_id  bigint not null,
  name          text default '',
  domain        text default '',
  icon          text default '',
  enterprise_id text default '',
  bot_token_enc bytea,
  key_version   bigint not null default 1,
  bot_user_id   text default '',
  bot_id        text default '',
  scopes        text default '',
  email_scope   bigint default 0,
  dm_scope      bigint default 0,
  installed_by  text default '',
  status        text default 'active',
  last_error    text default '',
  installed_at  text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  revoked_at    text
);
create table tool_calls (
  id          bigint generated by default as identity primary key,
  org_id bigint not null,
  team_id text not null default '', channel text, thread_ts text, name text, args text, result text, ok bigint, ms bigint,
  created_at  text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);
create table turns (
  id          bigint generated by default as identity primary key,
  team_id     text not null default '',
  channel     text not null,
  thread_ts   text not null,
  role        text not null,
  user_id     text,
  content     text not null,
  slack_ts    text,
  tokens_in   bigint default 0,
  tokens_out  bigint default 0,
  created_at  text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);
create table usage (
  id          bigint generated by default as identity primary key,
  org_id bigint not null,
  team_id text not null default '', channel text, thread_ts text, model text,
  tokens_in bigint, tokens_out bigint, cost_usd double precision,
  created_at  text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
, user_id text default '');
create table user_connections (
  id            bigint generated by default as identity primary key,
  org_id        bigint not null,
  conn_id       bigint not null,
  team_id       text not null default '',
  slack_user_id text not null,
  account       text default '',
  secret_enc    bytea,
  status        text default 'active',
  created_at    text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at    text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  last_used     text
, instructions text not null default '');
create table user_identities (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null,
  provider   text not null,
  subject    text not null,
  created_at text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);
create table user_recovery_codes (
  id        bigint generated by default as identity primary key,
  user_id   bigint not null,
  code_hash text not null,
  used_at   text
);
create table user_totp (
  user_id      bigint primary key,
  secret_enc   bytea not null,
  confirmed_at text,
  last_step    bigint not null default 0,
  created_at   text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
);
create table users (
  id             bigint generated by default as identity primary key,
  public_id      text not null default '',
  email          text not null,
  email_verified bigint not null default 0,
  password_hash  text default '',
  name           text default '',
  status         text not null default 'active',
  created_at     text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  last_seen      text
);
create table web_keys (
  org_id     bigint not null,
  provider   text not null,
  secret_enc bytea,
  updated_by text not null default '',
  updated_at text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  primary key (org_id, provider)
);
create index access_requests_open on access_requests(status, expires_at);
create index access_requests_thread on access_requests(channel, thread_ts);
create unique index api_keys_hash on api_keys(key_hash);
create index api_keys_org on api_keys(org_id);
create unique index approval_members_uniq on approval_members(org_id, role_id, ref);
create index artifacts_thread on artifacts(team_id, channel, thread_ts);
create index artifacts_time on artifacts(created_at);
create index connections_bundle on connections(bundle_id);
create unique index console_roles_key on console_roles(org_id, key);
create unique index console_users_key on console_users(team_id, slack_user_id);
create index doc_chunks_doc on doc_chunks(org_id, doc_id);
create unique index document_folders_path on document_folders(org_id, path);
create unique index documents_path on documents(org_id, path);
create unique index drive_sync_files_file on drive_sync_files(org_id, sync_id, file_id);
create index drive_sync_files_sync on drive_sync_files(org_id, sync_id);
create unique index drive_syncs_folder on drive_syncs(org_id, connection_id, folder_id);
create index email_tokens_user on email_tokens(user_id, kind);
create index github_installs_org on github_installs(org_id);
create index investigations_pending on investigations(status, lease_until, id);
create index investigations_thread on investigations(org_id, team_id, channel, thread_ts, status);
create unique index job_events_seq on job_events(job_id, seq);
create index job_files_job on job_files(job_id);
create index jobs_status on jobs(status);
create index jobs_thread on jobs(team_id, channel, thread_ts);
create unique index memberships_key on memberships(user_id, org_id);
create index memories_scope on memories(scope);
create unique index orgs_public_id on orgs(public_id);
create unique index orgs_slug on orgs(slug);
create index personal_memories_owner on personal_memories(org_id, team_id, owner, id);
create index proxy_audit_time on proxy_audit(created_at);
create index routine_runs_by_routine on routine_runs(org_id, routine_id, id desc);
create unique index scopes_key on scopes(org_id, kind, team_id, slack_id);
create index skills_bundle on skills(bundle_id);
create index slack_deliveries_pending on slack_deliveries(done_at, lease_until, accepted_at);
create index slack_deliveries_team on slack_deliveries(team_id, done_at);
create index turns_thread on turns(team_id, channel, thread_ts, id);
create unique index user_connections_key on user_connections(conn_id, team_id, slack_user_id);
create unique index user_identities_key on user_identities(provider, subject);
create index user_recovery_codes_user on user_recovery_codes(user_id);
create unique index users_email on users(email);
create unique index users_public_id on users(public_id);
