-- The Postgres twin of ../sqlite/0003_sso_providers.sql. Same table, same columns; blob
-- becomes bytea. See the SQLite file for why the domain index is partial.
-- Single sign-on: one organisation's identity provider.
--
-- An organisation registers its IdP here, and a sign-in is routed to it by the email domain the
-- provider claims. That claim is the whole security question, so it is deliberately in two
-- parts: registering writes the row, and proving the domain by DNS flips domain_verified. Until
-- it does, the provider is inert — nobody signs in through it — because a deployment with open
-- registration would otherwise let a stranger claim a domain they do not own and collect the
-- sign-ins of everybody who works there.
--
-- One provider per organisation (sso_providers_org). Sign-in routes on the domain, so a second
-- one would only matter to an organisation with two domains, which nobody has asked for.
create table sso_providers (
  id                bigint generated by default as identity primary key,
  org_id            bigint not null,
  provider_id       text not null,                 -- appears in our own callback URL
  kind              text not null default 'oidc',  -- 'oidc'; saml is not implemented
  domain            text not null,                 -- the email domain, lowercased and bare
  issuer            text not null,                 -- OIDC issuer; discovery hangs off it
  client_id         text not null,
  client_secret_enc bytea,                         -- sealed (crypto.go), never read back out
  domain_token      text not null default '',      -- the value of the TXT record we ask for
  domain_verified   integer not null default 0,
  created_by        bigint not null default 0,    -- users.id, for the audit trail
  created_at        text default (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
  verified_at       text
);
create unique index sso_providers_org on sso_providers(org_id);
create unique index sso_providers_pid on sso_providers(provider_id);

-- Exclusive only once proved. A unique index over every row would let an unverified claim on
-- example.com block the organisation that actually owns it — squatting, with no proof required.
-- Partial, so an unclaimed domain may be claimed by anyone and a proved one by exactly one.
create unique index sso_providers_domain on sso_providers(domain) where domain_verified = 1;
