-- The Postgres twin of ../sqlite/0004_audit_log.sql. Same table, same columns; integer becomes
-- bigint and the serial is an identity column, as everywhere else in this dialect.
--
-- See the SQLite file for what the table is for and why it is append-only.
create table audit_log (
  id           bigint generated by default as identity primary key,
  org_id       bigint not null,
  created_at   text not null,
  action       text not null,
  outcome      text not null default 'ok',
  via          text not null default '',
  actor_id     bigint not null default 0,
  actor_public text not null default '',
  actor_email  text not null default '',
  actor_name   text not null default '',
  actor_slack  text not null default '',
  team_id      text not null default '',
  target_kind  text not null default '',
  target_id    text not null default '',
  target_name  text not null default '',
  ip           text not null default '',
  user_agent   text not null default '',
  details      text not null default '{}'
);
create index audit_log_org_id on audit_log(org_id, id);
