-- The Postgres twin of ../sqlite/0006_assistant_turns.sql. Same table, same columns; integer
-- becomes bigint, real becomes double precision, and the serial is an identity column, as
-- everywhere else in this dialect.
--
-- See the SQLite file for what the table is for, and for why the console assistant's turns
-- cannot live in `turns` alongside Slack's.
create table assistant_turns (
  id           bigint generated by default as identity primary key,
  org_id       bigint not null,
  created_at   text not null default to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  actor        text not null default '',
  actor_name   text not null default '',
  conversation text not null default '',
  question     text not null default '',
  reply        text not null default '',
  model        text not null default '',
  page         text not null default '',
  tokens_in    bigint not null default 0,
  tokens_out   bigint not null default 0,
  cost_usd     double precision not null default 0,
  tool_calls   bigint not null default 0,
  proposals    bigint not null default 0,
  error        text not null default ''
);

create index assistant_turns_org_idx on assistant_turns (org_id, id desc);
