-- The Postgres twin of ../sqlite/0009_billing.sql. Same tables, same columns; integer becomes
-- bigint and the serial is an identity column, as everywhere else in this dialect.
--
-- See the SQLite file for what the three tables are, why the balance is materialised rather than
-- computed, why the money is integer micro-dollars, and why credit_ledger.external_id is unique
-- across the deployment rather than within an organisation.
create table billing_accounts (
  org_id                bigint primary key,
  provider              text not null default 'stripe',
  customer_id           text not null default '',
  subscription_id       text not null default '',
  status                text not null default '',
  band                  text not null default '',
  unit_price_micros     bigint not null default 0,
  quantity              bigint not null default 0,
  currency              text not null default 'usd',
  period_start          text not null default '',
  period_end            text not null default '',
  cancel_at_period_end  bigint not null default 0,
  credit_balance_micros bigint not null default 0,
  credit_enforced       bigint not null default 0,
  lifetime_topup_micros bigint not null default 0,
  lifetime_debit_micros bigint not null default 0,
  debit_rolled_micros   bigint not null default 0,
  created_at            text not null,
  updated_at            text not null
);
create unique index billing_accounts_customer on billing_accounts(customer_id);

create table credit_ledger (
  id                   bigint generated by default as identity primary key,
  org_id               bigint not null,
  created_at           text not null,
  kind                 text not null,
  amount_micros        bigint not null,
  balance_after_micros bigint not null,
  currency             text not null default 'usd',
  external_id          text not null,
  note                 text not null default '',
  actor                text not null default ''
);
create unique index credit_ledger_external on credit_ledger(external_id);
create index credit_ledger_org on credit_ledger(org_id, id);

create table billing_events (
  event_id    text primary key,
  provider    text not null default 'stripe',
  type        text not null default '',
  received_at text not null
);
create index billing_events_received on billing_events(received_at);
