-- The Postgres twin of ../sqlite/0024_mcp_oauth.sql: the MCP server's clients, authorization
-- codes and grants. Same columns; integer becomes bigint, as everywhere else in this dialect.
--
-- See the SQLite file for what each table and column holds.
create table mcp_clients (
  id            text primary key,
  name          text not null default '',
  redirect_uris text not null,
  auth_method   text not null default 'none',
  secret_hash   text not null default '',
  created_at    text not null,
  last_used_at  text not null default ''
);

create table mcp_codes (
  code_hash       text primary key,
  client_id       text not null,
  org_id          bigint not null,
  user_id         bigint not null,
  redirect_uri    text not null,
  code_challenge  text not null,
  scope           text not null default '',
  resource        text not null default '',
  expires_at      text not null,
  used_at         text not null default '',
  grant_id        bigint not null default 0
);

create table mcp_grants (
  id                  bigint generated by default as identity primary key,
  org_id              bigint not null,
  user_id             bigint not null,
  client_id           text not null,
  client_name         text not null default '',
  redirect_uri        text not null default '',
  scope               text not null default '',
  resource            text not null default '',
  access_hash         text not null,
  access_expires_at   text not null,
  refresh_hash        text not null,
  refresh_expires_at  text not null,
  prev_refresh_hash   text not null default '',
  created_at          text not null,
  last_used_at        text not null default '',
  revoked_at          text not null default ''
);
create unique index mcp_grants_access on mcp_grants (access_hash);
create unique index mcp_grants_refresh on mcp_grants (refresh_hash);
create index mcp_grants_prev_refresh on mcp_grants (prev_refresh_hash);
create index mcp_grants_org on mcp_grants (org_id, id);
