-- The Postgres twin of ../sqlite/0027_code_review.sql: the GitHub inbox, review settings, review
-- types and their rules and versions, and the pull requests, runs and findings of code review,
-- plus the own-key opt-in for reviews. Same columns and the same index names; integer becomes
-- bigint, real becomes double precision and blob becomes bytea, as everywhere else in this
-- dialect.
--
-- See the SQLite file for what each table and column holds and why.
create table github_deliveries (
  delivery_id     text primary key,
  org_id          bigint not null default 0,
  installation_id bigint not null default 0,
  event           text not null,
  action          text not null default '',
  payload_enc     bytea,
  accepted_at     bigint not null,
  lease_until     bigint not null default 0,
  attempts        bigint not null default 0,
  done_at         bigint not null default 0,
  dead_at         bigint not null default 0,
  last_error      text not null default ''
);
create index github_deliveries_pending on github_deliveries (done_at, dead_at, lease_until, accepted_at);
create index github_deliveries_installation on github_deliveries (org_id, installation_id, accepted_at);

create table review_settings (
  id              bigint generated by default as identity primary key,
  org_id          bigint not null,
  public_id       text not null,
  kind            text not null,
  parent_id       bigint,
  installation_id bigint not null default 0,
  name            text not null default '',
  repo            text not null default '',
  settings_json   text not null default '{}',
  removed_at      text,
  updated_by      text not null default '',
  created_at      text not null,
  updated_at      text not null
);
create unique index review_settings_public_id on review_settings (public_id);
create unique index review_settings_connection on review_settings (org_id, installation_id) where kind = 'connection';
create unique index review_settings_repo on review_settings (org_id, repo) where kind = 'repo';
create unique index review_settings_group on review_settings (org_id, parent_id, name) where kind = 'group';
create index review_settings_parent on review_settings (org_id, parent_id);

create table review_types (
  id                  bigint generated by default as identity primary key,
  org_id              bigint not null,
  public_id           text not null,
  key                 text not null,
  builtin_key         text,
  name                text not null,
  purpose             text not null default '',
  path_globs_json     text not null default '[]',
  strictness          text not null default '',
  model               text not null default '',
  max_usd             double precision not null default 0,
  inline_min_severity text not null default '',
  enabled             bigint not null default 1,
  version             bigint not null default 1,
  updated_by          text not null default '',
  created_at          text not null,
  updated_at          text not null
);
create unique index review_types_key on review_types (org_id, key);
create unique index review_types_public_id on review_types (public_id);

create table review_type_rules (
  id               bigint generated by default as identity primary key,
  org_id           bigint not null,
  public_id        text not null,
  type_id          bigint not null,
  position         bigint not null default 0,
  text             text not null,
  severity_cap     text not null default '',
  path_globs_json  text not null default '[]',
  example_bad      text not null default '',
  example_good     text not null default '',
  enabled          bigint not null default 1,
  source           text not null default 'team',
  status           text not null default 'active',
  from_comment_url text not null default '',
  created_at       text not null,
  updated_at       text not null
);
create unique index review_type_rules_public_id on review_type_rules (public_id);
create index review_type_rules_type on review_type_rules (org_id, type_id, position);

create table review_type_versions (
  id            bigint generated by default as identity primary key,
  org_id        bigint not null,
  type_id       bigint not null,
  version       bigint not null,
  snapshot_json text not null,
  created_by    text not null default '',
  created_at    text not null
);
create unique index review_type_versions_key on review_type_versions (org_id, type_id, version);

create table review_prs (
  id                 bigint generated by default as identity primary key,
  org_id             bigint not null,
  repo               text not null,
  pr_number          bigint not null,
  state              text not null default 'open',
  is_fork            bigint not null default 0,
  is_private         bigint not null default 0,
  author_login       text not null default '',
  head_sha           text not null default '',
  last_reviewed_sha  text not null default '',
  file_hashes        text not null default '{}',
  paused             bigint not null default 0,
  auto_reviews       bigint not null default 0,
  reviews_count      bigint not null default 0,
  score              bigint not null default -1,
  summary_comment_id bigint not null default 0,
  body_mirror        text not null default '',
  skip_reason        text not null default '',
  lease_until        bigint not null default 0,
  updated_at         text not null
);
create unique index review_prs_key on review_prs (org_id, repo, pr_number);

create table review_runs (
  id               bigint generated by default as identity primary key,
  public_id        text not null,
  org_id           bigint not null,
  review_pr_id     bigint not null,
  repo             text not null,
  pr_number        bigint not null,
  kind             text not null default 'review',
  dedupe_key       text not null,
  trigger          text not null default '',
  trigger_ref      text not null default '',
  requested_by     text not null default '',
  head_sha         text not null default '',
  base_sha         text not null default '',
  cache_key        text not null default '',
  types_json       text not null default '[]',
  rule_label       text not null default '',
  config_hash      text not null default '',
  status           text not null default 'queued',
  not_before       bigint not null default 0,
  lease_until      bigint not null default 0,
  attempts         bigint not null default 0,
  cancel           bigint not null default 0,
  reserved_usd     double precision not null default 0,
  github_review_id bigint not null default 0,
  files_reviewed   bigint not null default 0,
  not_reviewed     text not null default '[]',
  candidates       bigint not null default 0,
  dropped          bigint not null default 0,
  kept             bigint not null default 0,
  score            bigint not null default -1,
  summary          text not null default '',
  risk             text not null default '',
  model            text not null default '',
  tokens_in        bigint not null default 0,
  tokens_out       bigint not null default 0,
  tokens_cached    bigint not null default 0,
  cost_usd         double precision not null default 0,
  error            text not null default '',
  created_at       text not null,
  started_at       text not null default '',
  finished_at      text not null default ''
);
create unique index review_runs_public_id on review_runs (public_id);
create unique index review_runs_dedupe on review_runs (org_id, review_pr_id, dedupe_key);
create index review_runs_claim on review_runs (status, not_before, lease_until);
create index review_runs_org on review_runs (org_id, id);

create table review_findings (
  id                  bigint generated by default as identity primary key,
  public_id           text not null,
  org_id              bigint not null,
  review_pr_id        bigint not null,
  first_run_id        bigint not null default 0,
  last_run_id         bigint not null default 0,
  review_type         text not null default '',
  review_types        text not null default '[]',
  path                text not null,
  side                text not null default 'RIGHT',
  start_line          bigint not null default 0,
  line                bigint not null default 0,
  anchor_sha          text not null default '',
  code_hash           text not null default '',
  placement           text not null default '',
  kind                text not null default '',
  severity            text not null default '',
  category            text not null default '',
  title               text not null default '',
  body                text not null default '',
  suggestion          text not null default '',
  evidence            text not null default '',
  rule_refs           text not null default '[]',
  pre_existing        bigint not null default 0,
  fingerprint         text not null default '',
  verifier_confidence bigint not null default 0,
  status              text not null default 'open',
  status_reason       text not null default '',
  status_by           text not null default '',
  claimed_fixed_sha   text not null default '',
  claimed_by          text not null default '',
  github_comment_id   bigint not null default 0,
  thread_node_id      text not null default '',
  bot_replies         bigint not null default 0,
  created_at          text not null,
  updated_at          text not null
);
create unique index review_findings_public_id on review_findings (public_id);
create index review_findings_pr on review_findings (org_id, review_pr_id, status);
create index review_findings_comment on review_findings (org_id, github_comment_id);

alter table org_model_keys add column reviews bigint not null default 0;
