package app

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"context"
	"fmt"
	"maps"
	"net/http"
	"net/url"
	"regexp"
	"slices"
	"strings"
	"testing"
	"time"

	"attesttag/internal/review"
)

// grep searches a copy of the pull request's head that a review downloads once, as GitHub's archive
// of that commit. These pin what the copy keeps, how far it goes before it says it is partial, what a
// search answers — masked, numbered as read_file numbers, capped — and how the download goes out:
// under the read-only token to GitHub's API, and bare to the host GitHub redirects to.

// archiveEntry is one entry of a test archive: a file unless typ says otherwise.
type archiveEntry struct {
	name, body string
	typ        byte
}

// tarGz is an archive the way GitHub writes one: a global header naming the commit, then every entry
// under one top directory.
func tarGz(t *testing.T, top string, entries ...archiveEntry) []byte {
	t.Helper()
	var buf bytes.Buffer
	gz := gzip.NewWriter(&buf)
	tw := tar.NewWriter(gz)
	must := func(err error) {
		if err != nil {
			t.Fatal(err)
		}
	}
	must(tw.WriteHeader(&tar.Header{Typeflag: tar.TypeXGlobalHeader, Name: "pax_global_header",
		PAXRecords: map[string]string{"comment": reviewHead}}))
	must(tw.WriteHeader(&tar.Header{Typeflag: tar.TypeDir, Name: top + "/", Mode: 0o755}))
	for _, e := range entries {
		h := &tar.Header{Typeflag: tar.TypeReg, Name: top + "/" + e.name, Mode: 0o644, Size: int64(len(e.body))}
		if e.typ != 0 {
			h.Typeflag, h.Size, h.Linkname = e.typ, 0, "elsewhere"
		}
		must(tw.WriteHeader(h))
		if h.Typeflag == tar.TypeReg {
			_, err := tw.Write([]byte(e.body))
			must(err)
		}
	}
	must(tw.Close())
	must(gz.Close())
	return buf.Bytes()
}

// archiveFiles are a path → content map as archive entries, in path order.
func archiveFiles(m map[string]string) []archiveEntry {
	var out []archiveEntry
	for _, k := range slices.Sorted(maps.Keys(m)) {
		out = append(out, archiveEntry{name: k, body: m[k]})
	}
	return out
}

func indexPaths(ix *reviewHeadIndex) []string {
	var out []string
	for _, f := range ix.files {
		out = append(out, f.path)
	}
	return out
}

// grepRun is a run with only what grep's keep rule reads: the settings' ignored paths.
func grepRun(ignore ...string) *reviewRun {
	return &reviewRun{spec: reviewSpec{Settings: review.Effective{IgnorePaths: ignore}}}
}

// The copy holds the text a reviewer would look a definition up in, and nothing else: no installed
// packages, build output, vendored or generated code, lockfiles, minified files, binaries, files
// larger than a review keeps, credential files, links, or what the team ignores.
func TestReviewHeadIndexKeepsTheTextWorthSearching(t *testing.T) {
	big := strings.Repeat("x", int(reviewIndexLimits.fileMax)+1)
	arch := tarGz(t, "acme-web-aaaaaaa",
		archiveEntry{name: "src/totals.go", body: totalsHead},
		archiveEntry{name: "src/util.go", body: "package totals\r\n\r\nfunc helper() {}\r\n"},
		archiveEntry{name: "README.md", body: "# web\n"},
		archiveEntry{name: "node_modules/left-pad/index.js", body: "module.exports = 1\n"},
		archiveEntry{name: "web/dist/app.js", body: "var a = 1\n"},
		archiveEntry{name: "build/out.txt", body: "built\n"},
		archiveEntry{name: "vendor/lib/x.go", body: "package lib\n"},
		archiveEntry{name: "web/app.min.js", body: "var a=1\n"},
		archiveEntry{name: "package-lock.json", body: "{}\n"},
		archiveEntry{name: "img/logo.png", body: "\x89PNG\r\n\x1a\n\x00\x00\x00"},
		archiveEntry{name: "data/huge.txt", body: big},
		archiveEntry{name: "api/api.go", body: "// Code generated by protoc. DO NOT EDIT.\npackage api\n"},
		archiveEntry{name: ".env", body: "TOKEN=abc\n"},
		archiveEntry{name: "legacy/old.go", body: "package legacy\n"},
		archiveEntry{name: "src/link.go", typ: tar.TypeSymlink},
	)
	r := grepRun("legacy/**")
	ix, err := buildHeadIndex(context.Background(), reviewHead, bytes.NewReader(arch), reviewIndexLimits, r.grepKeeps)
	if err != nil {
		t.Fatal(err)
	}
	if got, want := indexPaths(ix), []string{"README.md", "src/totals.go", "src/util.go"}; !slices.Equal(got, want) {
		t.Errorf("kept %v, want %v", got, want)
	}
	if ix.partial != "" {
		t.Errorf("a small archive read whole says it is partial: %q", ix.partial)
	}
	// CRLF is read as LF, so a line's number is the one read_file gives it.
	if out := ix.search(context.Background(), "acme/web", regexp.MustCompile(`(?m)helper`), "helper", "", 40); !strings.Contains(out, "src/util.go:3: func helper() {}") {
		t.Errorf("a CRLF file's line came back as:\n%s", out)
	}
}

// Past any cap the copy stops where it got to and says why, so every answer from it can say it was
// partial; a download that breaks before any file was read is an error instead.
func TestReviewHeadIndexStopsAtItsCaps(t *testing.T) {
	var entries []archiveEntry
	for i := range 5 {
		entries = append(entries, archiveEntry{name: fmt.Sprintf("src/f%d.go", i), body: strings.Repeat("package f // padding\n", 50)})
	}
	arch := tarGz(t, "acme-web-aaaaaaa", entries...)
	keep := grepRun().grepKeeps
	for _, tc := range []struct {
		name  string
		caps  reviewIndexCaps
		files int
		why   string
	}{
		{"files", reviewIndexCaps{download: 1 << 30, kept: 1 << 30, files: 2, unpacked: 1 << 30, fileMax: 1 << 20}, 2, "more than the 2 files"},
		{"kept", reviewIndexCaps{download: 1 << 30, kept: 2500, files: 100, unpacked: 1 << 30, fileMax: 1 << 20}, 2, "more text than"},
		{"download", reviewIndexCaps{download: int64(len(arch) / 2), kept: 1 << 30, files: 100, unpacked: 1 << 30, fileMax: 1 << 20}, -1, "larger than"},
		{"unpacked", reviewIndexCaps{download: 1 << 30, kept: 1 << 30, files: 100, unpacked: 4000, fileMax: 1 << 20}, -1, "unpacks to more than"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			ix, err := buildHeadIndex(context.Background(), reviewHead, bytes.NewReader(arch), tc.caps, keep)
			if err != nil {
				t.Fatal(err)
			}
			if !strings.Contains(ix.partial, tc.why) {
				t.Errorf("partial = %q, want it to say %q", ix.partial, tc.why)
			}
			if tc.files >= 0 && len(ix.files) != tc.files {
				t.Errorf("kept %d files, want %d", len(ix.files), tc.files)
			}
			if len(ix.files) >= len(entries) {
				t.Errorf("kept all %d files past a cap", len(ix.files))
			}
			out := ix.search(context.Background(), "acme/web", regexp.MustCompile(`(?m)nothing like this`), "nothing like this", "", 40)
			if !strings.Contains(out, "Only part of the repository was searched: "+ix.partial) || !strings.Contains(out, "find_code") {
				t.Errorf("a search of a partial copy did not say so:\n%s", out)
			}
		})
	}
	if _, err := buildHeadIndex(context.Background(), reviewHead, strings.NewReader("\x1f\x8bnot gzip at all"), reviewIndexLimits, keep); err == nil {
		t.Error("an archive that is not one read as an empty copy")
	}
}

// A search is a regular expression, or plain text when literal; path narrows it to a directory, a
// glob over the path, or a glob over the file's name at any depth; what it shows is capped, and the
// rest is counted, by lines and by files.
func TestReviewGrepSearch(t *testing.T) {
	token := "ghp_" + strings.Repeat("x1", 18)
	arch := tarGz(t, "acme-web-aaaaaaa", archiveFiles(map[string]string{
		"src/auth/check.go":   "package auth\n\nfunc Check(a.b int) {}\nfunc Checkaxb() {}\n",
		"src/auth/check.ts":   "export function Check() {}\n",
		"src/billing/plan.go": "package billing\n\nfunc plan() { auth.Check(1) }\n",
		"lib/keys.go":         "package lib\n\nconst key = \"" + token + "\" // Check\n",
		"web/index.ts":        "Check();\nCheck();\nCheck();\n",
	})...)
	ix, err := buildHeadIndex(context.Background(), reviewHead, bytes.NewReader(arch), reviewIndexLimits, grepRun().grepKeeps)
	if err != nil {
		t.Fatal(err)
	}
	r := &reviewRun{repo: "acme/web", head: reviewHead}
	r.grepIdx.index = ix
	ctx := context.Background()
	grep := func(args string) string {
		t.Helper()
		out, err := r.grep(ctx, args)
		if err != nil {
			t.Fatalf("grep %s: %v", args, err)
		}
		return out
	}

	out := grep(`{"pattern":"a.b"}`)
	if !strings.Contains(out, "src/auth/check.go:3: func Check(a.b int) {}") || !strings.Contains(out, "src/auth/check.go:4: func Checkaxb() {}") {
		t.Errorf("a regular expression did not match as one:\n%s", out)
	}
	out = grep(`{"pattern":"a.b","literal":"true"}`)
	if !strings.Contains(out, "src/auth/check.go:3:") || strings.Contains(out, "check.go:4:") || !strings.Contains(out, "1 matching lines in 1 files") {
		t.Errorf("a literal search matched more than its text:\n%s", out)
	}
	if !strings.HasPrefix(out, "acme/web @ aaaaaaa (the pull request's head): 1 matching lines") {
		t.Errorf("the first line, which the trace keeps, does not say what was searched:\n%s", out)
	}

	for glob, want := range map[string][]string{
		"src/auth":    {"src/auth/check.go", "src/auth/check.ts"},
		"src/**/*.go": {"src/auth/check.go", "src/billing/plan.go"},
		"*.ts":        {"src/auth/check.ts", "web/index.ts"},
		"lib/keys.go": {"lib/keys.go"},
	} {
		out := grep(fmt.Sprintf(`{"pattern":"Check","path":%q}`, glob))
		var got []string
		for _, l := range strings.Split(out, "\n")[1:] {
			if p, _, ok := strings.Cut(l, ":"); ok && strings.Contains(l, ": ") && !slices.Contains(got, p) {
				got = append(got, p)
			}
		}
		if !slices.Equal(got, want) {
			t.Errorf("path %q searched %v, want %v:\n%s", glob, got, want, out)
		}
	}
	if out := grep(`{"pattern":"Check","path":"nowhere/"}`); !strings.Contains(out, "No line of") || !strings.Contains(out, "No text file is under that path") {
		t.Errorf("a path with no files under it was not said to be one:\n%s", out)
	}

	// The copy is raw, and what is shown of it is masked.
	if out := grep(`{"pattern":"const key"}`); strings.Contains(out, token) || !strings.Contains(out, "lib/keys.go:3: const key = \""+reviewMask) {
		t.Errorf("a credential in the head was shown, or its line was not:\n%s", out)
	}

	out = grep(`{"pattern":"Check\\(","max_results":"2"}`)
	if !strings.Contains(out, "6 matching lines in 4 files for \"Check\\\\(\", 2 shown") || !strings.Contains(out, "4 more matches in 2 files") {
		t.Errorf("a capped search did not count what it did not show:\n%s", out)
	}

	for args, want := range map[string]string{
		`{"pattern":"("}`:          "not a regular expression",
		`{"pattern":"  "}`:         "say what to search for",
		`{"pattern":"x","path":5}`: "not a JSON object",
		`{"pattern":"` + strings.Repeat("a", reviewGrepPattern+1) + `"}`: "at most",
	} {
		if _, err := r.grep(ctx, args); err == nil || !strings.Contains(err.Error(), want) {
			t.Errorf("grep %.60s: err = %v, want %q", args, err, want)
		}
	}
}

// What a grep shows fits in one tool result, however many lines match and however long they are.
func TestReviewGrepFitsInAToolResult(t *testing.T) {
	m := map[string]string{}
	for i := range 30 {
		m[fmt.Sprintf("src/f%02d.go", i)] = strings.Repeat("needle "+strings.Repeat("y", 400)+"\n", 10)
	}
	arch := tarGz(t, "acme-web-aaaaaaa", archiveFiles(m)...)
	ix, err := buildHeadIndex(context.Background(), reviewHead, bytes.NewReader(arch), reviewIndexLimits, grepRun().grepKeeps)
	if err != nil {
		t.Fatal(err)
	}
	out := ix.search(context.Background(), "acme/web", regexp.MustCompile(`(?m)needle`), "needle", "", reviewGrepMax)
	if len(out) > reviewToolOutputChars {
		t.Errorf("a grep answered %d characters, past the %d a tool result holds", len(out), reviewToolOutputChars)
	}
	if !strings.Contains(out, "300 matching lines in 30 files") || !strings.Contains(out, "more matches in") {
		t.Errorf("a search cut short by size did not say what it left out:\n%.400s", out)
	}
	for _, l := range strings.Split(out, "\n")[1:] {
		if _, text, ok := strings.Cut(l, ": "); ok && len(text) > reviewGrepLineChars {
			t.Errorf("a line was shown at %d characters, past %d", len(text), reviewGrepLineChars)
		}
	}
}

// A pattern that matches nothing at all matches every line once, and no line past the last newline.
func TestReviewGrepLinesCountsLinesOnce(t *testing.T) {
	var got []int
	grepLines(context.Background(), "a\nbb\n\nc\n", regexp.MustCompile(`(?m)x*`), func(n int, _ string) { got = append(got, n) })
	if !slices.Equal(got, []int{1, 2, 3, 4}) {
		t.Errorf("an empty match counted lines %v, want 1-4", got)
	}
	got = nil
	grepLines(context.Background(), "one two two\nthree\ntwo", regexp.MustCompile(`(?m)two`), func(n int, _ string) { got = append(got, n) })
	if !slices.Equal(got, []int{1, 3}) {
		t.Errorf("matched lines %v, want 1 and 3, each once", got)
	}
}

// A pattern that runs to the end of whatever it is matched against — [^;]* in code with no
// semicolons — is matched a line at a time, so a large file takes as long as reading it once; and a
// search whose time is up stops.
func TestReviewGrepLinesStaysLinearAndStopsOnTime(t *testing.T) {
	text := strings.Repeat("foo := bar(baz) // no semicolons here at all\n", 12_000) // ~500 KB
	start := time.Now()
	n := 0
	grepLines(context.Background(), text, regexp.MustCompile(`foo[^;]*`), func(int, string) { n++ })
	if n != 12_000 || time.Since(start) > 2*time.Second {
		t.Errorf("%d lines matched in %s", n, time.Since(start))
	}
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	n = 0
	grepLines(ctx, text, regexp.MustCompile(`foo`), func(int, string) { n++ })
	if n >= 12_000 {
		t.Errorf("a search whose time was up matched all %d lines", n)
	}
}

// A review greps forty times at most, finder and verifier together.
func TestReviewGrepIsCappedPerReview(t *testing.T) {
	r := &reviewRun{repo: "acme/web", head: reviewHead}
	r.grepIdx.index = &reviewHeadIndex{sha: reviewHead}
	for range reviewGrepMaxCalls {
		if _, err := r.grep(context.Background(), `{"pattern":"x"}`); err != nil {
			t.Fatal(err)
		}
	}
	if _, err := r.grep(context.Background(), `{"pattern":"x"}`); err == nil || !strings.Contains(err.Error(), "40 greps") {
		t.Errorf("err = %v, want the cap said", err)
	}
}

// The copy goes when the run ends, and nothing builds it again after.
func TestReviewGrepIndexIsReleased(t *testing.T) {
	var g reviewGrepIndex
	built := 0
	build := func(context.Context) (*reviewHeadIndex, error) {
		built++
		return &reviewHeadIndex{sha: reviewHead}, nil
	}
	for range 3 {
		if ix, err := g.get(context.Background(), build); err != nil || ix == nil {
			t.Fatalf("get = %v, %v", ix, err)
		}
	}
	g.release()
	if ix, err := g.get(context.Background(), build); err == nil || ix != nil || built != 1 {
		t.Errorf("after release: %v, %v, built %d times; want an error and one build", ix, err, built)
	}
}

func TestReviewGrepGlob(t *testing.T) {
	for _, tc := range []struct {
		glob, path string
		want       bool
	}{
		{"", "a/b.go", true},
		{"src", "src/a.go", true},
		{"src/", "src/a/b.go", true},
		{"src", "srcx/a.go", false},
		{"./src/a.go", "src/a.go", true},
		{"*.go", "deep/in/a.go", true},
		{"*.go", "a.ts", false},
		{"src/*.go", "src/a/b.go", false},
		{"src/**/*.go", "src/a/b.go", true},
		{"/src/**", "src/x", true},
	} {
		if got := grepGlob(tc.glob, tc.path); got != tc.want {
			t.Errorf("grepGlob(%q, %q) = %v, want %v", tc.glob, tc.path, got, tc.want)
		}
	}
}

// serveArchive serves fx.head as GitHub does: the API redirects to the download host, which serves
// the archive to anybody holding the signed URL. It counts the archives served.
func (rig *reviewRig) serveArchive() *int {
	f, n := rig.gh, new(int)
	f.mux.HandleFunc("GET /repos/acme/web/tarball/{sha}", func(w http.ResponseWriter, r *http.Request) {
		if got := f.permsOf(r); got != readPerms {
			rig.t.Errorf("the archive was asked for with a token for %q, want the read-only %q", got, readPerms)
		}
		w.Header().Set("Location", "https://codeload.github.com/acme/web/legacy.tar.gz/"+r.PathValue("sha")+"?token=SIGNED")
		w.WriteHeader(http.StatusFound)
	})
	f.mux.HandleFunc("GET codeload.github.com/acme/web/legacy.tar.gz/{sha}", func(w http.ResponseWriter, r *http.Request) {
		if a := r.Header.Get("Authorization"); a != "" {
			rig.t.Errorf("the download host was sent the installation token: %q", a)
		}
		if r.PathValue("sha") != reviewHead || r.URL.Query().Get("token") != "SIGNED" {
			rig.t.Errorf("downloaded %s, want the head through the URL GitHub signed", r.URL)
		}
		*n++
		w.Write(tarGz(rig.t, "acme-web-aaaaaaa", archiveFiles(rig.fx.head)...))
	})
	return n
}

// The whole way: the finder greps twice and the verifier once, and the head is downloaded once for
// all three — under the read-only token from the API, bare from the download host. Both tools are
// the finder's and the verifier's, and each grep is in the trace.
func TestReviewEngineGrepsTheHead(t *testing.T) {
	rig := newReviewRig(t, totalsFixture())
	downloads := rig.serveArchive()
	rig.model.finder["general"] = func(n int, q reviewModelReq) reviewModelReply {
		switch n {
		case 0:
			return reviewModelReply{Calls: []reviewCall{{"grep", map[string]any{"pattern": "t.value = 0", "literal": true}}}}
		case 1:
			return reviewModelReply{Calls: []reviewCall{{"grep", map[string]any{"pattern": `func \(t \*Totals\)`, "path": "src"}}}}
		}
		return submitFindings(lockFinding())
	}
	var verifierTools []string
	rig.model.verify = func(q reviewModelReq) reviewModelReply {
		verifierTools = q.Tools
		if len(q.ToolResults) == 0 {
			return reviewModelReply{Calls: []reviewCall{{"grep", map[string]any{"pattern": "mu.Lock"}}}}
		}
		return verdict("confirmed", 90, candidateOf(q).Severity)
	}
	out, err := rig.run(rig.spec("general"))
	if err != nil {
		t.Fatal(err)
	}
	if *downloads != 1 {
		t.Errorf("the head was downloaded %d times, want once for the whole run", *downloads)
	}
	finds := rig.model.requests("finder")
	if !slices.Contains(finds[0].Tools, "grep") || !slices.Contains(finds[0].Tools, "file_history") {
		t.Errorf("the finder's tools are %v", finds[0].Tools)
	}
	if !slices.Contains(verifierTools, "grep") || !slices.Contains(verifierTools, "file_history") || slices.Contains(verifierTools, "list_files") {
		t.Errorf("the verifier's tools are %v", verifierTools)
	}
	if res := strings.Join(finds[1].ToolResults, "\n"); !strings.Contains(res, "src/other.go:4: t.value = 0") {
		t.Errorf("the finder's grep did not find the line at the head:\n%s", res)
	}
	if res := strings.Join(finds[2].ToolResults, "\n"); !strings.Contains(res, "src/totals.go:11: func (t *Totals) Add(n int) {") ||
		!strings.Contains(res, "src/totals.go:16: func (t *Totals) Get() int {") {
		t.Errorf("a regular expression under a path did not find both methods:\n%s", res)
	}
	greps := 0
	for _, s := range out.Trace {
		if s.Tool == "grep" {
			greps++
			if s.Error || !strings.Contains(s.Result, "(the pull request's head)") {
				t.Errorf("a grep's trace line is %+v", s)
			}
		}
	}
	if greps != 3 {
		t.Errorf("the trace holds %d greps, want 3: %+v", greps, out.Trace)
	}
	for _, s := range rig.gh.sent() {
		if strings.Contains(s, "tarball") && !strings.HasPrefix(s, "GET /repos/acme/web/tarball/"+reviewHead) {
			t.Errorf("the archive was asked for as %s, want the head's commit", s)
		}
	}
}

// A head that cannot be downloaded is said to be, once, and grep points the model at the tools that
// still work; the review goes on.
func TestReviewEngineGrepWithoutAnArchive(t *testing.T) {
	rig := newReviewRig(t, totalsFixture())
	asked := 0
	rig.gh.mux.HandleFunc("GET /repos/acme/web/tarball/{sha}", func(w http.ResponseWriter, r *http.Request) {
		asked++
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte(`{"message":"Not Found"}`))
	})
	rig.model.finder["general"] = func(n int, q reviewModelReq) reviewModelReply {
		if n < 2 {
			return reviewModelReply{Calls: []reviewCall{{"grep", map[string]any{"pattern": fmt.Sprintf("Add%d", n)}}}}
		}
		return submitFindings()
	}
	if _, err := rig.run(rig.spec("general")); err != nil {
		t.Fatal(err)
	}
	finds := rig.model.requests("finder")
	res := strings.Join(finds[1].ToolResults, "\n")
	if !strings.HasPrefix(res, "error: grep could not read the pull request's head") || !strings.Contains(res, "find_code searches the default branch") {
		t.Errorf("a failed download answered:\n%s", res)
	}
	if asked != 1 {
		t.Errorf("the archive was asked for %d times, want once a run", asked)
	}
}

// The archive is read at a commit and nowhere else, and its redirect is followed only to where GitHub
// serves archives from.
func TestReviewGitHubArchiveIsHeldToTheCommit(t *testing.T) {
	c, f := reviewGitHubFixture(t)
	for _, tc := range []struct {
		rel  string
		want bool
	}{
		{"tarball/" + reviewHead, true},
		{"tarball/main", false},
		{"tarball/" + reviewHead + "/x", false},
		{"zipball/" + reviewHead, false},
		{"commits?sha=" + reviewBase + "&path=src%2Fa.go&per_page=10", true},
		{"commits?sha=" + reviewBase + "&author=someone", false},
		{"commits/" + reviewBase, false},
	} {
		u, _ := url.Parse(c.base + "/repos/acme/web/" + tc.rel)
		if err := c.allow("GET", u); (err == nil) != tc.want {
			t.Errorf("GET %s: allowed %v, want %v (%v)", tc.rel, err == nil, tc.want, err)
		}
	}
	if _, err := c.Archive(context.Background(), "main"); err == nil {
		t.Error("an archive of a branch name was asked for")
	}
	f.mux.HandleFunc("GET /repos/acme/web/tarball/{sha}", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Location", "https://downloads.example.com/acme/web.tar.gz")
		w.WriteHeader(http.StatusFound)
	})
	f.mux.HandleFunc("GET downloads.example.com/", func(w http.ResponseWriter, r *http.Request) {
		t.Errorf("the redirect to another host was followed, with Authorization %q", r.Header.Get("Authorization"))
	})
	if _, err := c.Archive(context.Background(), reviewHead); err == nil || !strings.Contains(err.Error(), "not where GitHub serves archives from") {
		t.Errorf("err = %v, want the redirect refused", err)
	}
}
