#!/usr/bin/env python3
"""Run deploy/aws/*.sh, deploy/azure/*.sh and deploy/gcp/*.sh against fake CLIs and assert on
what they did.

Usage:  ./deploy/test/run.sh [-v] [name-filter]

Each scenario gets a throwaway env file of obvious fakes and a fresh state directory, with
deploy/test/fakes first on PATH so `aws`, `az`, `gcloud` and `docker` resolve to the recorders.
Nothing here touches a cloud account, the repository's own .env, or the network.

The AWS and Azure scripts are run with whatever bash is first on PATH. On macOS that is 3.2, which
is the oldest they claim to support and the version deploy/aws/worker.sh warns about by name.
The gcp scripts run under zsh, their shebang.
"""
import json
import os
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[2]
FAKES = ROOT / "deploy" / "test" / "fakes"
VERBOSE = "-v" in sys.argv
FILTER = next((a for a in sys.argv[1:] if not a.startswith("-")), "")

# Values written into the throwaway env file. Every one is recognisably fake, and the harness
# asserts none of them reaches stdout — "never print a secret" is a rule worth a test.
SECRETS = {
    "MASTER_KEY": "FAKEmasterkeyFAKEmasterkeyFAKEmasterkey0000=",
    "SLACK_SIGNING_SECRET": "fake0signing0secret0000000000000",
    "SLACK_CLIENT_ID": "1234567890.0987654321",
    "SLACK_CLIENT_SECRET": "fake0client0secret00000000000000",
    "OPENROUTER_API_KEY": "sk-or-v1-fakefakefakefakefakefake",
    "RESEND_API_KEY": "re_fake_00000000000000000",
    "HEALTH_SECRET": "fake0health0secret",
    "OPERATOR_SECRET": "fake0operator0secret",
}
PLAIN = {
    "ALLOWED_EMAIL_DOMAINS": "example.com",
    "MAIL_FROM": "bot@example.com",
    "TZ_NAME": "UTC",
    "SIGNUP_MODE": "invite",
}

results = []
REGISTERED = []


class Fail(Exception):
    pass


class Run:
    """One invocation of a deploy script, plus everything the fakes recorded about it."""

    def __init__(self, state, script, env, stdout, stderr, code):
        self.state_dir = state
        self.script = script
        self.env = env
        self.stdout = stdout
        self.stderr = stderr
        self.code = code

    @property
    def output(self):
        return self.stdout + self.stderr

    def calls(self, tool=None):
        f = self.state_dir / "calls.log"
        if not f.exists():
            return []
        rows = [json.loads(line) for line in f.read_text().splitlines() if line.strip()]
        return [r for r in rows if tool is None or r[0] == tool]

    def called(self, *words):
        """Was there a call whose argv contains all of these words, in order?"""
        for row in self.calls():
            joined = " ".join(row)
            if all(w in joined for w in words):
                idx = [joined.index(w) for w in words]
                if idx == sorted(idx):
                    return row
        return None

    def count(self, key):
        f = self.state_dir / "state.json"
        if not f.exists():
            return 0
        return json.loads(f.read_text()).get("_counters", {}).get(key, 0)

    def capture(self, name):
        f = self.state_dir / "captures" / name
        return f.read_text() if f.exists() else None

    def captures(self, pattern):
        d = self.state_dir / "captures"
        if not d.exists():
            return []
        return sorted(p.name for p in d.iterdir() if re.search(pattern, p.name))


def env_file(path, drop=(), extra=None):
    lines = ["# throwaway — generated by deploy/test/harness.py, never a real credential"]
    for k, v in list(SECRETS.items()) + list(PLAIN.items()):
        if k in drop:
            continue
        lines.append("%s=%s" % (k, v))
    for k, v in (extra or {}).items():
        lines.append("%s=%s" % (k, v))
    path.write_text("\n".join(lines) + "\n")
    return path


def run(script, *, state=None, env=None, drop=(), extra_env=None, env_extra=None, stdin="",
        tty_answer=None, shell="bash"):
    """Run a deploy script with the fakes on PATH. `state` reuses a previous run's registry."""
    fresh = state is None
    state = state or pathlib.Path(tempfile.mkdtemp(prefix="deploycloud-"))
    # A reused state directory keeps the first run's resources but takes a new env file whenever
    # this run asks for different settings — that is how a scenario runs worker.sh and then the
    # deploy script against the same account with the worker switched on.
    if fresh or drop or env_extra:
        env_file(state / "env", drop=drop, extra=env_extra)

    e = dict(os.environ)
    e["PATH"] = "%s:%s" % (FAKES, e["PATH"])
    e["FAKE_CLOUD_STATE"] = str(state)
    # Always explicit: the scripts default ENV_FILE to the repository's real .env, and a test
    # that fell through to it would read live credentials.
    e["ENV_FILE"] = str(state / "env")
    e.pop("AWS_PROFILE", None)
    e.update(env or {})

    if tty_answer is None:
        # stdin is a closed pipe unless a scenario says otherwise, so `[ -t 0 ]` is
        # deterministically false: the CREATE_DATABASE confirmation must refuse rather than
        # block a whole test run on a prompt nobody is going to answer.
        p = subprocess.run([shell, str(ROOT / script)], cwd=str(ROOT), env=e,
                           input=stdin, capture_output=True, text=True, timeout=120)
        return Run(state, script, e, p.stdout, p.stderr, p.returncode)

    # A real terminal, because that is the only way `[ -t 0 ]` is true and the prompt is
    # reached at all. This is the path a person actually takes.
    import pty
    master, slave = pty.openpty()
    proc = subprocess.Popen([shell, str(ROOT / script)], cwd=str(ROOT), env=e, stdin=slave,
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    os.close(slave)
    os.write(master, tty_answer.encode())
    try:
        stdout, stderr = proc.communicate(timeout=120)
    finally:
        os.close(master)
    return Run(state, script, e, stdout, stderr, proc.returncode)


# ── assertions ───────────────────────────────────────────────────────────────────────────────
def ok(cond, msg):
    if not cond:
        raise Fail(msg)


def scenario(name):
    """Register a scenario. Registration only — main() runs them, so importing this file to
    poke at one scenario does not run all forty."""
    def deco(fn):
        REGISTERED.append((name, fn))
        return fn
    return deco


def no_secret_leaked(r):
    for key, value in SECRETS.items():
        if value in r.output:
            raise Fail("the value of %s appeared in the script output" % key)


def show(r):
    if VERBOSE:
        print("\n--- %s exit=%d ---\n%s\n%s---\n" % (r.script, r.code, r.stdout, r.stderr))


# ═════════════════════════════════════════════════════════════════════════════════════════════
# AWS — what the script refuses to do
# ═════════════════════════════════════════════════════════════════════════════════════════════

@scenario("aws: refuses to deploy without DOMAIN")
def _():
    r = run("deploy/aws/fargate.sh")
    ok(r.code != 0, "expected a non-zero exit with no DOMAIN, got 0")
    ok("DOMAIN is required" in r.output, "no explanation of what DOMAIN is for")
    ok(r.called("sts", "get-caller-identity") is None or len(r.calls("aws")) <= 1,
       "it reached AWS before checking its own arguments")


@scenario("aws: refuses to deploy without MASTER_KEY")
def _():
    r = run("deploy/aws/fargate.sh", env={"DOMAIN": "bot.example.com"}, drop=("MASTER_KEY",))
    ok(r.code != 0, "deployed without MASTER_KEY — every stored credential would be unreadable")
    ok("MASTER_KEY is missing" in r.output, "did not say which key was missing")
    ok(r.count("docker:push") == 0, "pushed an image before noticing")


@scenario("aws: refuses to deploy without the Slack OAuth pair")
def _():
    for key in ("SLACK_CLIENT_ID", "SLACK_CLIENT_SECRET"):
        r = run("deploy/aws/fargate.sh", env={"DOMAIN": "bot.example.com"}, drop=(key,))
        ok(r.code != 0, "deployed without %s; the service would refuse to start" % key)
        ok(key in r.output, "did not name %s" % key)
        ok("oauth/callback" in r.output, "did not say what to register in Slack")


@scenario("aws: refuses one public subnet, because an ALB needs two zones")
def _():
    r = run("deploy/aws/fargate.sh",
            env={"DOMAIN": "bot.example.com", "FAKE_AWS_SUBNETS": "subnet-0aaa"})
    ok(r.code != 0, "accepted a single subnet; the ALB would fail to create")
    ok("availability zones" in r.output, "did not explain why two are needed")


@scenario("aws: refuses when there is no default VPC")
def _():
    r = run("deploy/aws/fargate.sh",
            env={"DOMAIN": "bot.example.com", "FAKE_AWS_NO_DEFAULT_VPC": "1"})
    ok(r.code != 0, "carried on with no VPC")
    ok("VPC_ID" in r.output, "did not say which variable to set")


@scenario("aws: stops on a certificate that is not issued yet, before building anything")
def _():
    r = run("deploy/aws/fargate.sh", env={"DOMAIN": "bot.example.com",
                                          "FAKE_AWS_CERT_STATUS": "PENDING_VALIDATION"})
    ok(r.code != 0, "carried on with an unvalidated certificate")
    ok("Add this CNAME" in r.output, "did not tell the operator what record to add")
    ok(r.called("elbv2", "create-load-balancer") is None,
       "created a load balancer it could not attach a certificate to")


# ═════════════════════════════════════════════════════════════════════════════════════════════
# AWS — what the script produces
# ═════════════════════════════════════════════════════════════════════════════════════════════

def aws_deploy(**kw):
    r = run("deploy/aws/fargate.sh", env={"DOMAIN": "bot.example.com", **kw.pop("env", {})}, **kw)
    ok(r.code == 0, "fargate.sh exited %d\n%s" % (r.code, r.stderr[-800:]))
    return r


@scenario("aws: deploys end to end and hands back the CNAME")
def _():
    r = aws_deploy()
    show(r)
    ok("CNAME" in r.stdout and "elb.amazonaws.com" in r.stdout, "no DNS instruction in the output")
    ok(r.called("ecs", "create-service"), "no service was created")


@scenario("aws: the service enforces the one-writer rule")
def _():
    r = aws_deploy()
    svc = r.capture("ecs-create-service.txt")
    ok(svc, "no create-service call was captured")
    ok("minimumHealthyPercent=0,maximumPercent=100" in svc,
       "the deployment configuration would allow two tasks against one SQLite replica")
    ok("--desired-count 1" in svc, "desired count is not 1")


@scenario("aws: the task definition gives the lease time to be released")
def _():
    td = json.loads(aws_deploy().capture("taskdef-attesttag-1.json"))
    stop = td["containerDefinitions"][0].get("stopTimeout")
    ok(stop == 45, "stopTimeout is %r; the write lease wants ~9s to be released cleanly" % stop)


@scenario("aws: no task role is attached while the fix worker is off")
def _():
    td = json.loads(aws_deploy().capture("taskdef-attesttag-1.json"))
    ok("taskRoleArn" not in td,
       "the bot was given an AWS identity it has no use for: %r" % td.get("taskRoleArn"))
    ok(td["executionRoleArn"].endswith("role/attesttag-exec"), "wrong execution role")


@scenario("aws: every secret travels by reference, never in the environment")
def _():
    r = aws_deploy()
    td = json.loads(r.capture("taskdef-attesttag-1.json"))
    container = td["containerDefinitions"][0]
    names = {s["name"] for s in container["secrets"]}
    ok("MASTER_KEY" in names and "SLACK_SIGNING_SECRET" in names,
       "MASTER_KEY or SLACK_SIGNING_SECRET is not among the secrets: %s" % sorted(names))
    for s in container["secrets"]:
        ok(s["valueFrom"].startswith("arn:aws:secretsmanager:"),
           "%s is not a Secrets Manager reference" % s["name"])
        ok(s["valueFrom"].endswith(":%s::" % s["name"]),
           "%s does not select its own JSON key: %s" % (s["name"], s["valueFrom"]))
    env_blob = json.dumps(container["environment"])
    for key, value in SECRETS.items():
        ok(value not in env_blob, "%s appears as a plain environment value" % key)
    no_secret_leaked(r)


@scenario("aws: the database defaults to SQLite replicated to the bucket")
def _():
    r = aws_deploy()
    td = json.loads(r.capture("taskdef-attesttag-1.json"))
    env = {e["name"]: e["value"] for e in td["containerDefinitions"][0]["environment"]}
    ok(env.get("DOCS_S3_URL", "").startswith("s3://attesttag-data-123456789012/docs?region="),
       "DOCS_S3_URL is %r; without it the task loses its database on every restart"
       % env.get("DOCS_S3_URL"))
    ok(env.get("DOCS_S3_KEY_ID", "").startswith("AKIA"), "no S3 key id was passed")
    names = {s["name"] for s in td["containerDefinitions"][0]["secrets"]}
    ok("DATABASE_URL" not in names, "a DATABASE_URL leaked in from somewhere")
    ok("DB_PATH" not in env, "DB_PATH is set explicitly; the binary's default is the contract")


@scenario("aws: DATABASE_URL switches it to Postgres and is carried as a secret")
def _():
    url = "postgres://u:p@db.example.com:5432/attesttag?sslmode=require"
    r = aws_deploy(env_extra={"DATABASE_URL": url})
    td = json.loads(r.capture("taskdef-attesttag-1.json"))
    container = td["containerDefinitions"][0]
    names = {s["name"] for s in container["secrets"]}
    ok("DATABASE_URL" in names, "DATABASE_URL was not passed; the deploy would stay on SQLite")
    ok(url not in json.dumps(container["environment"]),
       "the Postgres URL, which carries a password, was passed as a plain environment value")


@scenario("aws: the load balancer health-checks /health and http only redirects")
def _():
    r = aws_deploy()
    tg = r.capture("target-group-attesttag.txt")
    ok("--health-check-path /health" in tg, "the target group does not health-check /health")
    ok("--target-type ip" in tg, "awsvpc tasks need target-type ip")
    l80 = r.capture("listener-80.txt")
    ok(l80 and "redirect" in l80 and "HTTPS" in l80,
       "port 80 does not redirect to https; the console sets Secure cookies")
    l443 = r.capture("listener-443.txt")
    ok(l443 and "CertificateArn=arn:aws:acm" in l443, "the https listener has no certificate")


@scenario("aws: rerunning mints no second access key and rolls the existing service")
def _():
    first = aws_deploy()
    second = run("deploy/aws/fargate.sh", state=first.state_dir, env={"DOMAIN": "bot.example.com"})
    ok(second.code == 0, "the second run exited %d\n%s" % (second.code, second.stderr[-800:]))
    ok(second.count("iam:create-access-key") == 1,
       "a second access key was minted; the one in Secrets Manager is the one the task uses")
    ok(second.count("s3:create-bucket") == 1, "tried to create the bucket twice")
    ok(second.count("elbv2:create-load-balancer") == 1, "tried to create a second load balancer")
    ok(second.count("elbv2:create-listener:443") == 1, "tried to create a second https listener")
    ok(second.count("ecs:update-service") == 1 and second.count("ecs:create-service") == 1,
       "the rerun did not roll the existing service")
    ok(second.count("ecs:register:attesttag") == 2, "no new task definition revision")


# ═════════════════════════════════════════════════════════════════════════════════════════════
# AWS — the fix-job worker, and the handshake between the two scripts
# ═════════════════════════════════════════════════════════════════════════════════════════════

@scenario("aws worker: registers both definitions and builds for x86_64")
def _():
    r = run("deploy/aws/worker.sh")
    ok(r.code == 0, "worker.sh exited %d\n%s" % (r.code, r.stderr[-800:]))
    ok(r.count("ecs:register:attesttag-worker") == 1, "no worker task definition")
    ok(r.count("ecs:register:attesttag-worker-jvm") == 1, "no heavy worker task definition")
    for row in r.calls("docker"):
        if row[1] == "build":
            ok("--platform" in row and "linux/amd64" in row,
               "an image was built without --platform linux/amd64; Fargate would exec-format-error")
    td = json.loads(r.capture("taskdef-attesttag-worker-1.json"))
    c = td["containerDefinitions"][0]
    ok(c["name"] == "worker",
       "the container is named %r; internal/app/jobs_ecs.go overrides a container called worker"
       % c["name"])
    ok(td.get("ephemeralStorage", {}).get("sizeInGiB") == 50,
       "no enlarged ephemeral storage; a clone plus a cold dependency install exceeds the default")


@scenario("aws worker: WORKER_JVM=0 skips the heavy image")
def _():
    r = run("deploy/aws/worker.sh", env={"WORKER_JVM": "0"})
    ok(r.code == 0, "worker.sh exited %d" % r.code)
    ok(r.count("ecs:register:attesttag-worker") == 1, "no worker task definition")
    ok(r.count("ecs:register:attesttag-worker-jvm") == 0, "built the heavy image anyway")


@scenario("aws worker: the worker's own role is granted nothing")
def _():
    r = run("deploy/aws/worker.sh")
    ok(r.code == 0, "worker.sh exited %d" % r.code)
    granted = [c for c in r.captures(r"iam-role-policy-attesttag-worker-task")]
    ok(not granted, "the worker task role was given a policy: %s" % granted)
    for row in r.calls("aws"):
        if row[1:3] == ["iam", "attach-role-policy"]:
            ok("attesttag-worker-task" not in row, "a managed policy was attached to the worker role")


@scenario("aws worker: the bot may start these definitions and nothing else")
def _():
    r = run("deploy/aws/worker.sh")
    pol = json.loads(r.capture("iam-role-policy-attesttag-task-run-fix-workers.json"))
    runtask = [s for s in pol["Statement"] if s["Action"] == "ecs:RunTask"][0]
    ok(runtask["Resource"] != "*", "RunTask is unscoped — the bot could start any task definition")
    ok(all("task-definition/attesttag-worker" in a for a in runtask["Resource"]),
       "RunTask reaches beyond the worker definitions: %s" % runtask["Resource"])
    ok("ArnEquals" in runtask.get("Condition", {}), "RunTask is not conditioned on the cluster")
    passrole = [s for s in pol["Statement"] if s["Action"] == "iam:PassRole"][0]
    ok(len(passrole["Resource"]) == 2 and all("worker" in a for a in passrole["Resource"]),
       "PassRole is not limited to the two worker roles: %s" % passrole["Resource"])
    stop = [s for s in pol["Statement"] if "ecs:StopTask" in s["Action"]][0]
    ok("ArnEquals" in stop.get("Condition", {}),
       "DescribeTasks/StopTask are Resource:* with no cluster condition")


@scenario("aws: WORKER_MODE with no worker deployed warns instead of shipping a broken tool")
def _():
    r = aws_deploy(env={"WORKER_MODE": "workers"})
    ok("run deploy/aws/worker.sh" in r.output,
       "the fix tool was turned on with no task definition and nothing said so")


@scenario("aws: worker.sh then fargate.sh wires the bot to the worker with no warnings")
def _():
    w = run("deploy/aws/worker.sh")
    ok(w.code == 0, "worker.sh exited %d" % w.code)
    r = run("deploy/aws/fargate.sh", state=w.state_dir,
            env={"DOMAIN": "bot.example.com", "WORKER_MODE": "workers"})
    ok(r.code == 0, "fargate.sh exited %d\n%s" % (r.code, r.stderr[-800:]))
    ok("warning" not in r.stderr.lower(),
       "the two scripts did not agree: %s" % r.stderr.strip()[:400])
    td = json.loads(r.capture("taskdef-attesttag-1.json"))
    ok(td.get("taskRoleArn", "").endswith("role/attesttag-task"),
       "the bot was not given the task role worker.sh created, so RunTask would be denied")
    env = {e["name"]: e["value"] for e in td["containerDefinitions"][0]["environment"]}
    ok(env.get("WORKER_MODE") == "workers", "WORKER_MODE did not reach the container")
    ok(env.get("WORKER_ECS_CLUSTER") == "attesttag", "no cluster for the worker")
    ok(env.get("WORKER_ECS_SUBNETS"), "no subnets for the worker; the task would never start")
    ok(env.get("WORKER_ECS_SECURITY_GROUPS", "").startswith("sg-"),
       "no security group for the worker: %r" % env.get("WORKER_ECS_SECURITY_GROUPS"))


# ═════════════════════════════════════════════════════════════════════════════════════════════
# Azure
# ═════════════════════════════════════════════════════════════════════════════════════════════

S3_ENV = {"DOCS_S3_URL": "s3://bucket/docs?endpoint=https://acct.r2.cloudflarestorage.com&region=auto",
          "DOCS_S3_KEY_ID": "fakekeyid", "DOCS_S3_SECRET": "fake-r2-secret"}
PG_ENV = {"DATABASE_URL": "postgres://u:p@srv.postgres.database.azure.com:5432/attesttag?sslmode=require"}


def azure_deploy(env_extra, **kw):
    r = run("deploy/azure/containerapps.sh", env=kw.pop("env", {}), env_extra=env_extra, **kw)
    ok(r.code == 0, "containerapps.sh exited %d\n%s" % (r.code, r.stderr[-800:]))
    return r


def spec_of(r):
    import yaml
    body = r.capture("containerapp-spec.yaml")
    ok(body, "no Container Apps spec was captured")
    try:
        return yaml.safe_load(body)
    except Exception as exc:  # noqa: BLE001
        raise Fail("the hand-rolled YAML writer produced something PyYAML cannot parse: %s" % exc)


@scenario("azure: refuses when neither a bucket nor a Postgres is configured")
def _():
    r = run("deploy/azure/containerapps.sh")
    ok(r.code != 0, "deployed with nowhere durable to put the database")
    ok("DOCS_S3_URL" in r.output and "DATABASE_URL" in r.output, "did not offer both options")
    ok("Azure Files is SMB" in r.output, "did not explain why the obvious Azure answer is wrong")


@scenario("azure: refuses a second replica while the rows are in SQLite")
def _():
    r = run("deploy/azure/containerapps.sh", env={"REPLICAS": "2"}, env_extra=S3_ENV)
    ok(r.code != 0, "allowed two replicas against one SQLite writer")
    ok("one writer" in r.output, "did not explain the single-writer rule")


@scenario("azure: refuses to deploy without MASTER_KEY")
def _():
    r = run("deploy/azure/containerapps.sh", drop=("MASTER_KEY",), env_extra=S3_ENV)
    ok(r.code != 0, "deployed without MASTER_KEY")
    ok("MASTER_KEY is missing" in r.output, "did not say which key was missing")


@scenario("azure: the hand-rolled YAML writer emits a spec that parses")
def _():
    doc = spec_of(azure_deploy(S3_ENV))
    ok(doc["type"] == "Microsoft.App/containerApps", "wrong resource type")
    ok(doc["properties"]["managedEnvironmentId"].startswith("/subscriptions/"),
       "the managed environment id is not a resource id")


@scenario("azure: the app is pinned warm at one replica")
def _():
    scale = spec_of(azure_deploy(S3_ENV))["properties"]["template"]["scale"]
    ok(scale["minReplicas"] == 1,
       "minReplicas is %r; scaling to zero means the dispatcher and scheduler never run"
       % scale["minReplicas"])
    ok(scale["maxReplicas"] == 1, "maxReplicas is %r with SQLite" % scale["maxReplicas"])


@scenario("azure: secrets are referenced, not inlined into the environment")
def _():
    r = azure_deploy(S3_ENV)
    doc = spec_of(r)
    cfg = doc["properties"]["configuration"]
    names = {s["name"] for s in cfg["secrets"]}
    ok("master-key" in names, "MASTER_KEY is not stored as the secret master-key: %s" % sorted(names))
    for n in names:
        ok(re.fullmatch(r"[a-z0-9-]+", n), "%r is not a legal Container Apps secret name" % n)
    env = doc["properties"]["template"]["containers"][0]["env"]
    by_name = {e["name"]: e for e in env}
    ok("secretRef" in by_name["MASTER_KEY"], "MASTER_KEY is passed as a literal value")
    for key, value in SECRETS.items():
        ok(not any(e.get("value") == value for e in env),
           "%s appears as a plain environment value in the spec" % key)
    no_secret_leaked(r)


@scenario("azure: ingress is external https with no insecure fallback")
def _():
    ing = spec_of(azure_deploy(S3_ENV))["properties"]["configuration"]["ingress"]
    ok(ing["external"] is True, "ingress is not external; Slack could not reach it")
    ok(ing["targetPort"] == 8080, "ingress targets port %r" % ing["targetPort"])
    ok(ing["allowInsecure"] is False, "http is allowed; the console sets Secure cookies")


@scenario("azure: the startup probe is generous enough for a restore from the bucket")
def _():
    probes = spec_of(azure_deploy(S3_ENV))["properties"]["template"]["containers"][0]["probes"]
    kinds = {p["type"]: p for p in probes}
    ok("Startup" in kinds and "Liveness" in kinds, "missing a startup or liveness probe")
    for p in probes:
        ok(p["httpGet"]["path"] == "/health", "a probe does not use /health")
    s = kinds["Startup"]
    budget = s["periodSeconds"] * s["failureThreshold"]
    ok(budget >= 180, "the startup budget is %ds; a cold replica restores SQLite first" % budget)


@scenario("azure: Postgres puts documents on Azure Files, and only then")
def _():
    r = azure_deploy(PG_ENV)
    doc = spec_of(r)
    tmpl = doc["properties"]["template"]
    ok(tmpl.get("volumes"), "no documents volume alongside Postgres")
    ok(tmpl["volumes"][0]["storageType"] == "AzureFile", "the documents volume is not Azure Files")
    mounts = tmpl["containers"][0].get("volumeMounts", [])
    ok(mounts and mounts[0]["mountPath"] == "/app/docs", "the share is not mounted at /app/docs")
    ok(r.called("az", "storage", "share-rm", "create"), "no file share was created")
    names = {s["name"] for s in doc["properties"]["configuration"]["secrets"]}
    ok("database-url" in names, "DATABASE_URL is not carried as a secret; it holds a password")


@scenario("azure: a bucket means no Azure storage account is created at all")
def _():
    r = azure_deploy(S3_ENV)
    doc = spec_of(r)
    ok(r.count("az:storage-account-create") == 0, "created an Azure storage account it does not need")
    ok(not doc["properties"]["template"].get("volumes"), "mounted a volume alongside a bucket")
    env = {e["name"]: e.get("value") for e in doc["properties"]["template"]["containers"][0]["env"]}
    ok(env.get("DOCS_S3_URL") == S3_ENV["DOCS_S3_URL"], "DOCS_S3_URL did not reach the container")


@scenario("azure: the app gets a managed identity only when the fix worker is on")
def _():
    off = spec_of(azure_deploy(S3_ENV))
    ok("identity" not in off, "an identity was created that is granted nothing")
    on = spec_of(azure_deploy(dict(S3_ENV, WORKER_MODE="workers")))
    ok(on.get("identity", {}).get("type") == "SystemAssigned",
       "no managed identity with the worker on; the app could not start a job")


@scenario("azure: the worker grant is a custom role scoped to the jobs")
def _():
    w = run("deploy/azure/worker.sh")
    ok(w.code == 0, "azure worker.sh exited %d\n%s" % (w.code, w.stderr[-800:]))
    r = run("deploy/azure/containerapps.sh", state=w.state_dir,
            env_extra=dict(S3_ENV, WORKER_MODE="workers"))
    ok(r.code == 0, "containerapps.sh exited %d\n%s" % (r.code, r.stderr[-800:]))
    ok("warning" not in r.stderr.lower(), "the two scripts disagreed: %s" % r.stderr.strip()[:300])
    role = json.loads(r.capture("role-definition.json"))
    ok(set(role["Actions"]) == {"Microsoft.App/jobs/read", "Microsoft.App/jobs/start/action",
                                "Microsoft.App/jobs/executions/read",
                                "Microsoft.App/jobs/executions/stop/action"},
       "the custom role grants more than starting and stopping a job: %s" % role["Actions"])
    ok(r.count("az:role-assignment-create") >= 1, "the identity was never granted the role")


@scenario("azure: the spec file holding every secret is mode 600 and removed")
def _():
    r = azure_deploy(S3_ENV)
    mode = json.loads((r.state_dir / "state.json").read_text())["spec-mode"]["containerapp"]
    ok(mode == "0o600", "the spec was mode %s while it held every secret" % mode)
    leftovers = [c for c in r.calls("az") if "--yaml" in c]
    for call in leftovers:
        path = call[call.index("--yaml") + 1]
        ok(not os.path.exists(path), "the spec file survived the script at %s" % path)


@scenario("azure: rerunning updates the app rather than creating a second one")
def _():
    first = azure_deploy(S3_ENV)
    suffix = spec_of(first)["properties"]["template"].get("revisionSuffix")
    second = run("deploy/azure/containerapps.sh", state=first.state_dir, env_extra=S3_ENV)
    ok(second.code == 0, "the second run exited %d\n%s" % (second.code, second.stderr[-800:]))
    ok(second.count("az:containerapp-create") == 1, "created the app twice")
    ok(second.count("az:containerapp-update") == 1, "the rerun did not update the app")
    # Container Apps makes a revision only when the template changes, so a rerun on the same tag
    # used to change nothing: :latest moved and the app kept the old image, and a rotated secret
    # never reached a replica. The suffix is the change, and it has to be a legal one.
    again = spec_of(second)["properties"]["template"].get("revisionSuffix")
    for s in (suffix, again):
        ok(s and re.fullmatch(r"[a-z][a-z0-9-]*[a-z0-9]", s) and "--" not in s,
           "%r is not a revision suffix Container Apps accepts" % s)
    ok(suffix != again, "the rerun carried the same revision suffix, so it would start no new revision")


@scenario("azure worker: images are built in the registry for x86_64")
def _():
    r = run("deploy/azure/worker.sh")
    ok(r.code == 0, "azure worker.sh exited %d\n%s" % (r.code, r.stderr[-800:]))
    builds = [c for c in r.calls("az") if c[1:3] == ["acr", "build"]]
    ok(len(builds) == 2, "expected two acr builds, saw %d" % len(builds))
    for b in builds:
        ok("--platform" in b and "linux/amd64" in b,
           "an image was built without --platform linux/amd64")
    ok(r.count("docker:build") == 0, "azure worker.sh shelled out to a local docker build")


@scenario("azure worker: creates the jobs once, then updates them")
def _():
    first = run("deploy/azure/worker.sh")
    ok(first.code == 0, "first run exited %d" % first.code)
    ok(first.count("az:job-create") == 2, "expected two jobs created")
    second = run("deploy/azure/worker.sh", state=first.state_dir)
    ok(second.code == 0, "second run exited %d\n%s" % (second.code, second.stderr[-800:]))
    ok(second.count("az:job-create") == 2, "created a job that already existed")
    ok(second.count("az:job-update") == 2, "the rerun did not update the jobs")
    create = second.capture("job-attesttag-worker-create.txt")
    ok("--replica-retry-limit 0" in create,
       "a retried replica would find the job already claimed and report a confusing failure")
    ok("--registry-identity" in create, "the job has no identity to pull its own image with")
    # containerapps.sh builds the app's settings from the env file alone, so the lines worker.sh
    # prints go there; it used to offer the shell as well, where they did nothing.
    ok("never from the shell" in second.stdout and "(or the environment)" not in second.stdout,
       "worker.sh does not say the settings go in the env file")


# ═════════════════════════════════════════════════════════════════════════════════════════════
# Google Cloud — what a deployment is when nobody said
# ═════════════════════════════════════════════════════════════════════════════════════════════

# What deploy/gcp/cloudrun.sh fills in for the maintainer's hosted service, and for nobody else.
HOSTED_POLICY = {
    "SIGNUP_MODE": "open",
    "SUPPORT_EMAIL": "support@attesttag.com",
    "SITE_URL": "https://attesttag.com",
    "FREE_PLAN_BUDGET_USD": "5",
    "ORG_MODEL_KEYS": "enterprise",
}


def fake_gcloud_first():
    # The calls in the gcp scripts that would cost anything are `gcloud run deploy --source .` and
    # `gcloud builds submit .`, which upload this checkout. So the fake has to be the gcloud that
    # resolves, or nothing runs.
    path = "%s:%s" % (FAKES, os.environ["PATH"])
    ok(shutil.which("gcloud", path=path) == str(FAKES / "gcloud"),
       "the fake gcloud is not first on PATH; refusing to run a gcp script against a real one")


# The scripts' shebang is zsh; they are valid bash too, which is the fallback where zsh is absent.
ZSH = shutil.which("zsh") or "bash"


def set_env_vars(argv):
    """--set-env-vars as gcloud reads it: split on the delimiter a ^…^ prefix names, else on commas
    (gcloud topic escaping), then each entry on its first `=`."""
    ok("--set-env-vars" in argv, "cloudrun.sh never reached gcloud run deploy")
    raw, delim = argv[argv.index("--set-env-vars") + 1], ","
    if raw.startswith("^") and "^" in raw[1:]:
        delim, raw = raw[1:].split("^", 1)
    return dict(p.split("=", 1) for p in raw.split(delim))


def gcp_deploy(name, extra=None, env=None, drop=("SIGNUP_MODE",), raw=None):
    """Run cloudrun.sh on an env file called `name`; return the run and the env vars it deployed.

    SIGNUP_MODE is left out of the env file unless a scenario puts it back, because what is under
    test is what the script picks when nobody said. The policy keys are blanked in the process
    environment for the same reason: a value exported in the shell running the tests would win.
    `raw`, when given, is the whole env file, written as it is.
    """
    fake_gcloud_first()
    state = pathlib.Path(tempfile.mkdtemp(prefix="deploycloud-"))
    if raw is None:
        env_file(state / name, drop=drop, extra=extra)
    else:
        (state / name).write_text(raw)
    blank = {k: "" for k in ["HOSTED", "MAX_INSTANCES", "WORKER_MODE", "WORKER_JOB_NAMES",
                             "WORKER_CACHE_BUCKET", "STRIPE_SIZES"] + list(HOSTED_POLICY)}
    r = run("deploy/gcp/cloudrun.sh", state=state, shell=ZSH,
            env={**blank, "ENV_FILE": str(state / name), "PROJECT": "fake-project", **(env or {})})
    show(r)
    ok(r.code == 0, "cloudrun.sh exited %d\n%s" % (r.code, r.stderr[-800:]))
    no_secret_leaked(r)
    return r, set_env_vars(json.loads(r.capture("run-deploy.json") or "[]"))


@scenario("gcp: a copy deployed as it comes is one organisation, whatever its env file is called")
def _():
    # .env is what bootstrap.sh writes. .env.prod is the name this script used to ask for, and the
    # one a downloader who read its first lines would pick. Neither may open signup.
    for name in (".env", ".env.prod"):
        r, envs = gcp_deploy(name)
        ok(envs.get("SIGNUP_MODE") == "first-run",
           "%s deployed SIGNUP_MODE=%s, not first-run" % (name, envs.get("SIGNUP_MODE")))
        for key, hosted in HOSTED_POLICY.items():
            if key != "SIGNUP_MODE":
                ok(envs.get(key) != hosted, "%s deployed the hosted %s=%s" % (name, key, hosted))
        ok("HOSTED policy ON" not in r.output, "%s announced the hosted policy" % name)
        ok("one organisation" in r.output, "%s did not say it deploys one organisation" % name)


@scenario("gcp: HOSTED=1, in the env file or the shell, is what deploys the hosted policy")
def _():
    for how in ({"extra": {"HOSTED": "1"}}, {"env": {"HOSTED": "1"}}):
        r, envs = gcp_deploy(".env.prod", **how)
        for key, hosted in HOSTED_POLICY.items():
            ok(envs.get(key) == hosted, "HOSTED=1 from the %s deployed %s=%s, not %s"
               % ("file" if "extra" in how else "shell", key, envs.get(key), hosted))
        ok("HOSTED policy ON" in r.output, "the hosted policy went on without saying so")


@scenario("gcp: HOSTED=0 is off, and SIGNUP_MODE in the env file beats HOSTED either way")
def _():
    # The warning this replaced told a self-host to set HOSTED=0, which the script then read as on.
    r, envs = gcp_deploy(".env.prod", env={"HOSTED": "0"})
    ok(envs.get("SIGNUP_MODE") == "first-run", "HOSTED=0 deployed SIGNUP_MODE=%s" % envs.get("SIGNUP_MODE"))
    ok("SUPPORT_EMAIL" not in envs, "HOSTED=0 deployed the hosted support address")
    r, envs = gcp_deploy(".env.prod", extra={"HOSTED": "1", "SIGNUP_MODE": "closed"})
    ok(envs.get("SIGNUP_MODE") == "closed", "the env file's SIGNUP_MODE lost to HOSTED=1")
    r, envs = gcp_deploy(".env", extra={"SIGNUP_MODE": "open"})
    ok(envs.get("SIGNUP_MODE") == "open", "a self-host that asked for open signup did not get it")


# A DSN naming a Cloud SQL socket, which is what cloudrun.sh's Postgres branch takes.
CLOUDSQL_URL = "postgres://attesttag:pw@/attesttag?host=/cloudsql/fake-project:us-central1:attesttag-pg"


@scenario("gcp: a comma-separated list reaches the service whole")
def _():
    # --set-env-vars splits on commas, so STRIPE_SIZES arrived as its first size plus a variable
    # called upto_25, and WORKER_JOB_NAMES — the only route to the heavy worker job — was not
    # passed at all.
    lists = {
        "STRIPE_SIZES": "upto_10=price_fake10:1900:500,upto_25=price_fake25:4900,over_250=:0",
        "WORKER_JOB_NAMES": "java=attesttag-worker-jvm,java-gradle=attesttag-worker-jvm,dotnet=attesttag-worker-jvm",
        "ALLOWED_EMAIL_DOMAINS": "example.com,example.org",
    }
    r, envs = gcp_deploy(".env", extra=dict(lists, WORKER_MODE="workers"))
    for key, value in lists.items():
        ok(envs.get(key) == value, "%s reached the service as %r, not %r" % (key, envs.get(key), value))
    for stray in ("upto_25", "over_250", "java-gradle", "dotnet", "example.org"):
        ok(stray not in envs, "a piece of a list arrived as a variable of its own: %s" % stray)
    ok("MAIL_FROM" in envs and envs["MAIL_FROM"] == PLAIN["MAIL_FROM"], "a plain setting was lost")


@scenario("gcp: a value holding the delimiter is refused, not cut in two")
def _():
    fake_gcloud_first()
    r = run("deploy/gcp/cloudrun.sh", shell=ZSH, env_extra={"MAIL_FROM": "attest|tag <bot@example.com>"},
            env={"PROJECT": "fake-project", "HOSTED": "", "SIGNUP_MODE": ""})
    ok(r.code != 0, "deployed a value that gcloud would have split in two")
    ok("MAIL_FROM contains '|'" in r.output, "did not say which setting to fix:\n%s" % r.output[-400:])
    ok(r.capture("run-deploy.json") is None, "reached gcloud run deploy anyway")


@scenario("gcp: on Postgres the fix-job cache still has a bucket, and the lease is not mentioned")
def _():
    r, envs = gcp_deploy(".env", extra={"DATABASE_URL": CLOUDSQL_URL, "WORKER_MODE": "workers"},
                         env={"MAX_INSTANCES": "3"})
    ok(envs.get("REQUIRE_POSTGRES") == "1", "Postgres without REQUIRE_POSTGRES")
    ok("LITESTREAM_BUCKET" not in envs, "Litestream was left on beside Postgres")
    # The cache defaults to the replica bucket, and Postgres has none: without this it was off.
    ok(envs.get("WORKER_CACHE_BUCKET") == "attesttag-data-fake-project",
       "the dependency cache has no bucket on Postgres: %r" % envs.get("WORKER_CACHE_BUCKET"))
    ok("503" not in r.output, "warned about the SQLite lease on a Postgres deployment")
    ok("lock.json" not in r.output and "litestream/" not in r.output,
       "pointed at a replica and a lease that Postgres does not have")
    # An env file that names a bucket of its own for the cache keeps it.
    r, envs = gcp_deploy(".env", extra={"DATABASE_URL": CLOUDSQL_URL, "WORKER_MODE": "workers",
                                        "WORKER_CACHE_BUCKET": "my-cache"})
    ok(envs.get("WORKER_CACHE_BUCKET") == "my-cache", "the env file's cache bucket was overridden")
    # And the worker off means no cache setting at all.
    r, envs = gcp_deploy(".env", extra={"DATABASE_URL": CLOUDSQL_URL})
    ok("WORKER_CACHE_BUCKET" not in envs, "a cache bucket was set with the worker off")


@scenario("gcp: on SQLite a second instance is warned about, and the logs line is a real command")
def _():
    r, envs = gcp_deploy(".env", env={"MAX_INSTANCES": "3"})
    ok("LITESTREAM_BUCKET" in envs and "REQUIRE_POSTGRES" not in envs, "not the SQLite shape")
    ok("answers 503" in r.output, "no warning that instances past the lease holder answer 503")
    ok("lock.json" in r.output, "no pointer to the write lease on SQLite")
    # `logs tail` is a beta command; the GA spelling the script used to print does not exist.
    ok("gcloud beta run services logs tail attesttag" in r.output, "no beta logs tail line")
    ok("gcloud run services logs read attesttag" in r.output, "no logs read line")
    ok("gcloud run services logs tail" not in r.output, "still prints the logs tail that is not a command")


@scenario("gcp worker: on a new project it makes the bot's account before granting it anything")
def _():
    fake_gcloud_first()
    # FAKE_GCLOUD_NEW_PROJECT makes the fake refuse a binding for an account nobody created, as
    # IAM does — which is where worker.sh stopped when it ran before cloudrun.sh ever had.
    r = run("deploy/gcp/worker.sh", shell=ZSH,
            env={"PROJECT": "fake-project", "REGION": "europe-west1", "FAKE_GCLOUD_NEW_PROJECT": "1",
                 "ENV_FILE": ""})
    show(r)
    ok(r.code == 0, "worker.sh exited %d on a new project\n%s" % (r.code, r.stderr[-800:]))
    calls = [" ".join(c) for c in r.calls("gcloud")]
    created = next((i for i, c in enumerate(calls) if "service-accounts create attesttag-run" in c), None)
    granted = next((i for i, c in enumerate(calls)
                    if "add-iam-policy-binding" in c and "attesttag-run@fake-project" in c), None)
    ok(created is not None, "the bot's account was never created")
    ok(granted is not None and created < granted, "the bot was granted something before its account existed")
    # The hints: into the env file, and the deploy line names the env file and the region.
    ok("  WORKER_MODE=workers" in r.stdout, "no WORKER_MODE line to put in the env file")
    ok("  WORKER_JOB_NAMES=java=attesttag-worker-jvm," in r.stdout, "no WORKER_JOB_NAMES line")
    ok("ENV_FILE=.env PROJECT=fake-project REGION=europe-west1 ./deploy/gcp/cloudrun.sh" in r.stdout,
       "the deploy line does not name the env file and the region:\n%s" % r.stdout[-600:])


# ═════════════════════════════════════════════════════════════════════════════════════════════
# Both
# ═════════════════════════════════════════════════════════════════════════════════════════════

def template_env(appended, extra_blank=()):
    """An env file as bootstrap.sh leaves it and a person then extends it: a line for every key,
    empty for each key in `appended` (and in `extra_blank`), and those values appended below."""
    lines = ["# throwaway — generated by deploy/test/harness.py, never a real credential"]
    lines += ["%s=" % k for k in extra_blank]
    for k, v in list(SECRETS.items()) + list(PLAIN.items()):
        lines.append("%s=%s" % (k, "" if k in appended else v))
    lines.append("# appended later")
    lines += ["%s=%s" % (k, v) for k, v in appended.items()]
    return "\n".join(lines) + "\n"


def state_with(text):
    state = pathlib.Path(tempfile.mkdtemp(prefix="deploycloud-"))
    (state / "env").write_text(text)
    return state


@scenario("both: a value appended below the template's empty line is the one deployed")
def _():
    # The template holds an empty line for every key. A value appended below it — by hand, by
    # CREATE_DATABASE=1, or by the binary writing a MASTER_KEY it generated — lost to that empty
    # line, because every script read the first one: a required key was refused as missing and an
    # optional one was silently not deployed.
    appended = {"MASTER_KEY": SECRETS["MASTER_KEY"], "MAIL_FROM": "appended@example.com"}

    r = run("deploy/aws/fargate.sh", state=state_with(template_env(appended)),
            env={"DOMAIN": "bot.example.com"})
    ok(r.code == 0, "fargate.sh refused an appended value: %d\n%s" % (r.code, r.stderr[-600:]))
    container = json.loads(r.capture("taskdef-attesttag-1.json"))["containerDefinitions"][0]
    env = {e["name"]: e["value"] for e in container["environment"]}
    ok(env.get("MAIL_FROM") == "appended@example.com", "fargate.sh deployed MAIL_FROM=%r" % env.get("MAIL_FROM"))
    ok("MASTER_KEY" in {s["name"] for s in container["secrets"]}, "fargate.sh lost the appended MASTER_KEY")

    # containerapps.sh reads the file twice over: the shell's envval for its checks, and the spec
    # writer's own for everything the app is given.
    r = run("deploy/azure/containerapps.sh",
            state=state_with(template_env(dict(appended, **S3_ENV), extra_blank=S3_ENV)))
    ok(r.code == 0, "containerapps.sh refused an appended value: %d\n%s" % (r.code, r.stderr[-600:]))
    doc = spec_of(r)
    env = {e["name"]: e.get("value") for e in doc["properties"]["template"]["containers"][0]["env"]}
    ok(env.get("DOCS_S3_URL") == S3_ENV["DOCS_S3_URL"], "containerapps.sh deployed DOCS_S3_URL=%r" % env.get("DOCS_S3_URL"))
    ok(env.get("MAIL_FROM") == "appended@example.com", "containerapps.sh deployed MAIL_FROM=%r" % env.get("MAIL_FROM"))
    names = {s["name"] for s in doc["properties"]["configuration"]["secrets"]}
    ok({"master-key", "docs-s3-secret"} <= names, "containerapps.sh lost an appended secret: %s" % sorted(names))

    r, envs = gcp_deploy(".env", raw=template_env(appended))
    ok(envs.get("MAIL_FROM") == "appended@example.com", "cloudrun.sh deployed MAIL_FROM=%r" % envs.get("MAIL_FROM"))
    # And the other way round: an empty line below a value does not take the value away.
    r, envs = gcp_deploy(".env", raw=template_env({}) + "MAIL_FROM=\n")
    ok(envs.get("MAIL_FROM") == PLAIN["MAIL_FROM"], "an empty line below MAIL_FROM blanked it")


@scenario("both: the GitHub App's public half and another model endpoint reach the container")
def _():
    # Neither script passed the App's id, slug or client id, so no GitHub App could be set up on
    # AWS or Azure, and LLM_API_KEY — the key for a model endpoint other than OpenRouter — was
    # dropped by both.
    plain = {"GITHUB_APP_ID": "123456", "GITHUB_APP_SLUG": "attest-tag-fake",
             "GITHUB_APP_CLIENT_ID": "Iv23liFAKE", "LLM_BASE_URL": "https://llm.example.com/v1",
             "LLM_MODEL": "fake/model"}
    llm_key = "sk-fake-llm-key-000000000000"

    r = aws_deploy(env_extra=dict(plain, LLM_API_KEY=llm_key))
    container = json.loads(r.capture("taskdef-attesttag-1.json"))["containerDefinitions"][0]
    env = {e["name"]: e["value"] for e in container["environment"]}
    for key, value in plain.items():
        ok(env.get(key) == value, "fargate.sh deployed %s=%r, not %r" % (key, env.get(key), value))
    ok("LLM_API_KEY" in {s["name"] for s in container["secrets"]}, "fargate.sh dropped LLM_API_KEY")
    ok(llm_key not in json.dumps(container["environment"]) and llm_key not in r.output,
       "fargate.sh put LLM_API_KEY somewhere other than the secret")

    r = azure_deploy(dict(S3_ENV, LLM_API_KEY=llm_key, **plain))
    doc = spec_of(r)
    env = {e["name"]: e for e in doc["properties"]["template"]["containers"][0]["env"]}
    for key, value in plain.items():
        ok(env.get(key, {}).get("value") == value, "containerapps.sh deployed %s=%r" % (key, env.get(key)))
    ok(env.get("LLM_API_KEY", {}).get("secretRef") == "llm-api-key", "containerapps.sh did not pass LLM_API_KEY as a secret")
    ok(llm_key not in r.output, "containerapps.sh printed LLM_API_KEY")

# ═════════════════════════════════════════════════════════════════════════════════════════════
# CREATE_DATABASE — the opt-in that creates a managed Postgres
# ═════════════════════════════════════════════════════════════════════════════════════════════

@scenario("aws: CREATE_DATABASE bills nobody without a yes")
def _():
    r = run("deploy/aws/fargate.sh", env={"DOMAIN": "bot.example.com", "CREATE_DATABASE": "1"})
    ok(r.code != 0, "created a monthly-billed database with no confirmation")
    ok("billable resources" in r.output, "did not list what it was about to create")
    ok("db.t4g.micro" in r.output and "month" in r.output, "did not say what it costs")
    ok(r.count("rds:create-db-instance") == 0, "created the instance anyway")
    ok(r.count("docker:push") == 0, "pushed an image before asking")


@scenario("aws: CREATE_DATABASE at a terminal creates it on yes and nothing on no")
def _():
    no = run("deploy/aws/fargate.sh", env={"DOMAIN": "bot.example.com", "CREATE_DATABASE": "1"},
             tty_answer="n\n")
    ok(no.code != 0, "a refusal at the prompt carried on anyway")
    ok(no.count("rds:create-db-instance") == 0, "created the database after being told not to")
    ok("Nothing was created" in no.output, "did not say that nothing was created")

    yes = run("deploy/aws/fargate.sh", env={"DOMAIN": "bot.example.com", "CREATE_DATABASE": "1"},
              tty_answer="y\n")
    ok(yes.code == 0, "a yes at the prompt still failed: %d\n%s" % (yes.code, yes.stderr[-800:]))
    ok(yes.count("rds:create-db-instance") == 1, "said yes and got no database")


@scenario("aws: CREATE_DATABASE creates a private RDS and wires DATABASE_URL through")
def _():
    r = run("deploy/aws/fargate.sh", env={"DOMAIN": "bot.example.com",
                                          "CREATE_DATABASE": "1", "ASSUME_YES": "1"})
    ok(r.code == 0, "fargate.sh exited %d\n%s" % (r.code, r.stderr[-900:]))
    create = r.capture("rds-create-db-instance.txt")
    ok(create, "no RDS instance was created")
    ok("--no-publicly-accessible" in create, "the database is reachable from the internet")
    ok("--storage-encrypted" in create, "the database is not encrypted at rest")
    ok("--backup-retention-period 7" in create, "no backups")
    ok("--db-name attesttag" in create, "no initial database was created")

    # Reachable from the task and from nothing else.
    grant = [c for c in r.calls("aws")
             if c[1:3] == ["ec2", "authorize-security-group-ingress"] and "5432" in c]
    ok(grant, "nothing was allowed to reach the database on 5432")
    ok("--source-group" in grant[0], "port 5432 was opened to a CIDR rather than to the task group")

    # The DSN reaches the env file, and from there the task definition, as a secret.
    env_text = (r.state_dir / "env").read_text()
    ok("DATABASE_URL=postgres://attesttag:" in env_text,
       "the DSN was not written back to the env file, so a rerun would create a second database")
    ok(".rds.amazonaws.com:5432/attesttag?sslmode=require" in env_text,
       "the DSN does not require TLS or does not name the instance endpoint")
    td = json.loads(r.capture("taskdef-attesttag-1.json"))
    container = td["containerDefinitions"][0]
    ok("DATABASE_URL" in {s["name"] for s in container["secrets"]},
       "DATABASE_URL never reached the task definition; the deploy would still be on SQLite")
    ok("postgres://" not in json.dumps(container["environment"]),
       "the DSN, which carries a password, was passed as a plain environment value")
    env = {e["name"]: e["value"] for e in container["environment"]}
    ok(env.get("DOCS_S3_URL"), "documents lost their bucket when the rows moved to Postgres")

    # The generated password is never printed, and never reaches the call transcript.
    password = env_text.split("DATABASE_URL=postgres://attesttag:")[1].split("@")[0]
    ok(len(password) >= 16, "the generated password is only %d characters" % len(password))
    ok(password not in r.output, "the generated database password was printed")
    ok(password not in (r.state_dir / "calls.log").read_text(),
       "the generated database password was written to the call transcript")


@scenario("aws: rerunning after CREATE_DATABASE creates no second database")
def _():
    first = run("deploy/aws/fargate.sh", env={"DOMAIN": "bot.example.com",
                                              "CREATE_DATABASE": "1", "ASSUME_YES": "1"})
    ok(first.code == 0, "the first run exited %d" % first.code)
    second = run("deploy/aws/fargate.sh", state=first.state_dir,
                 env={"DOMAIN": "bot.example.com", "CREATE_DATABASE": "1", "ASSUME_YES": "1"})
    ok(second.code == 0, "the rerun exited %d\n%s" % (second.code, second.stderr[-900:]))
    ok(second.count("rds:create-db-instance") == 1, "created a second RDS instance")
    ok((second.state_dir / "env").read_text().count("DATABASE_URL=") == 1,
       "the env file collected a second DATABASE_URL line")


@scenario("azure: CREATE_DATABASE bills nobody without a yes")
def _():
    r = run("deploy/azure/containerapps.sh", env={"CREATE_DATABASE": "1"})
    ok(r.code != 0, "created a monthly-billed database with no confirmation")
    ok("billable resources" in r.output, "did not list what it was about to create")
    ok(r.count("az:pg-create") == 0, "created the server anyway")


@scenario("azure: CREATE_DATABASE is a third answer to the storage question")
def _():
    # Neither a bucket nor a DSN, which is normally a refusal.
    r = run("deploy/azure/containerapps.sh", env={"CREATE_DATABASE": "1", "ASSUME_YES": "1"})
    ok(r.code == 0, "containerapps.sh exited %d\n%s" % (r.code, r.stderr[-900:]))
    create = r.capture("postgres-create.txt")
    ok(create, "no Flexible Server was created")
    ok("--public-access 0.0.0.0" in create,
       "no Azure-services firewall rule; Container Apps could not reach the server")
    ok("--tier Burstable" in create, "not the cheap tier by default")

    env_text = (r.state_dir / "env").read_text()
    ok("DATABASE_URL=postgres://attesttag:" in env_text, "the DSN was not written back")
    ok("sslmode=require" in env_text, "the DSN does not require TLS")
    doc = spec_of(r)
    names = {x["name"] for x in doc["properties"]["configuration"]["secrets"]}
    ok("database-url" in names, "DATABASE_URL never reached the app as a secret")
    # Postgres holds the rows, so documents need the Azure Files share.
    ok(doc["properties"]["template"].get("volumes"), "documents have nowhere to live")
    password = env_text.split("DATABASE_URL=postgres://attesttag:")[1].split("@")[0]
    ok(password not in r.output, "the generated database password was printed")
    ok(password not in (r.state_dir / "calls.log").read_text(),
       "the generated database password was written to the call transcript")


@scenario("azure: CREATE_DATABASE unblocks a second replica in the same run")
def _():
    # The replica ceiling is a consequence of SQLite, so it has to be judged after the database
    # exists — not before, when DATABASE_URL is still unset and every run looks like SQLite.
    r = run("deploy/azure/containerapps.sh",
            env={"REPLICAS": "2", "CREATE_DATABASE": "1", "ASSUME_YES": "1"})
    ok(r.code == 0, "refused two replicas against a Postgres it had just created: %d\n%s"
       % (r.code, r.stderr[-700:]))
    scale = spec_of(r)["properties"]["template"]["scale"]
    ok(scale["minReplicas"] == 2 and scale["maxReplicas"] == 2,
       "asked for two replicas and got %r" % scale)


@scenario("azure: rerunning after CREATE_DATABASE creates no second server")
def _():
    first = run("deploy/azure/containerapps.sh", env={"CREATE_DATABASE": "1", "ASSUME_YES": "1"})
    ok(first.code == 0, "the first run exited %d" % first.code)
    second = run("deploy/azure/containerapps.sh", state=first.state_dir,
                 env={"CREATE_DATABASE": "1", "ASSUME_YES": "1"})
    ok(second.code == 0, "the rerun exited %d\n%s" % (second.code, second.stderr[-900:]))
    ok(second.count("az:pg-create") == 1, "created a second Flexible Server")
    ok((second.state_dir / "env").read_text().count("DATABASE_URL=") == 1,
       "the env file collected a second DATABASE_URL line")


@scenario("both: shellcheck finds no errors in any deploy script")
def _():
    if not shutil.which("shellcheck"):
        raise Fail("shellcheck is not installed (brew install shellcheck)")
    scripts = sorted(str(p) for p in (ROOT / "deploy").rglob("*.sh"))
    p = subprocess.run(["shellcheck", "-S", "error", "-s", "bash"] + scripts,
                       capture_output=True, text=True, cwd=str(ROOT))
    ok(p.returncode == 0, "shellcheck reported errors:\n%s" % (p.stdout or p.stderr)[:2000])


def main():
    for name, fn in REGISTERED:
        if FILTER and FILTER not in name:
            continue
        try:
            fn()
            results.append((True, name, ""))
            print("  \033[32mPASS\033[0m  %s" % name)
        except Fail as exc:
            results.append((False, name, str(exc)))
            print("  \033[31mFAIL\033[0m  %s\n        %s" % (name, exc))
        except Exception as exc:  # noqa: BLE001 - a broken fake should read as a failed test
            results.append((False, name, repr(exc)))
            print("  \033[31mERROR\033[0m %s\n        %r" % (name, exc))

    passed = sum(1 for good, _, _ in results if good)
    failed = [(n, m) for good, n, m in results if not good]
    print("\n%d passed, %d failed" % (passed, len(failed)))
    if failed:
        print("\nfailures:")
        for name, msg in failed:
            print("  %s\n    %s" % (name, msg))
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
